'use client';
import {useState} from 'react';
import {Panel,SectionTabs} from './primitives';
import {useAdminResource} from './admin/use-admin-resource';
import {csrfToken} from '../lib/auth';
import type {AccountSecurityView as Data,MfaEnrolment as Enrolment} from '../../../contracts/generated/administration';
export async function accountCommand<T=unknown>(path:string,body:unknown,method='POST'):Promise<T>{const response=await fetch('/api/v1'+path,{method,cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':await csrfToken()},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});if(!response.ok){const problem=await response.json().catch(()=>({}));throw new Error(response.status===401?'Sign in again to continue.':`Unable to complete this action (${problem.code??response.status}). Check the details and use a fresh verification code.`);}return response.json();}
export function AccountWorkspace({tab}:{tab:string}){
 const r=useAdminResource<Data>('/account/security');const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[enrol,setEnrol]=useState<Enrolment>(),[codes,setCodes]=useState<string[]>();
 async function act(path:string,body:unknown,method='POST',logout=false){setBusy(true);setError('');try{const value=await accountCommand<{recoveryCodes?:string[]}>(path,body,method);setNotice('Saved.');if(value.recoveryCodes){setCodes(value.recoveryCodes);setEnrol(undefined);}else if(logout){window.location.replace(new URL('/login',window.location.origin).href);}else r.reload();return value;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const tabs=[['profile','Profile'],['password','Password'],['mfa','Two-factor authentication'],['sessions','Sessions & activity']];
 return <><div className="page-heading"><div><h1>Manage account</h1><p>Your profile and sign-in security</p></div></div><SectionTabs active={tab} items={tabs.map(([key,label])=>({key,label,href:`/account?tab=${key}`}))}/><div aria-live="polite">{notice&&<p className="notice">{notice}</p>}{(error||r.error)&&<p role="alert">{error||r.error}</p>}</div>
 {codes?<Panel title="Save your recovery codes" note="These codes are shown once. Keep them in a private password manager. Each code can be used once instead of an authenticator code."><ul>{codes.map(x=><li key={x}><code>{x}</code></li>)}</ul><p>MFA enrolment signs out existing sessions. Password changes and administrative security changes invalidate old recovery codes.</p><button className="button button-primary" onClick={()=>{setCodes(undefined);window.location.replace(new URL('/login',window.location.origin).href);}}>I saved the codes — sign in</button></Panel>:!r.data?<Panel title="Account"><p role="status">Loading account…</p></Panel>:<>
 {tab==='profile'&&<><Panel title="Your profile"><form className="task-form" key={r.data.etag} onSubmit={e=>{e.preventDefault();void act('/account/profile',{displayName:new FormData(e.currentTarget).get('name'),etag:r.data!.etag},'PUT');}}><label>Display name<input name="name" required maxLength={200} defaultValue={r.data.displayName}/></label><p>Email: {r.data.email}<br/>Roles: {r.data.currentRoles.join(', ')}</p><button className="button button-primary" disabled={busy}>Save profile</button></form></Panel>{!!r.data.teams.length&&<Panel title="Request an email, team or role change" note="A current administrator must approve protected changes. Applied changes end your existing sessions."><form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/account/identity-requests',{email:f.get('email'),teamId:f.get('team'),roles:f.getAll('roles'),reason:f.get('reason')});}}><label>Requested email<input type="email" name="email" required maxLength={254} defaultValue={r.data.email}/></label><label>Requested team<select name="team" defaultValue={r.data.teamId}>{r.data.teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><fieldset><legend>Requested roles</legend>{r.data.roles.map(x=><label className="task-checkbox" key={x}><input type="checkbox" name="roles" value={x} defaultChecked={r.data!.currentRoles.includes(x)}/>{x}</label>)}</fieldset><label>Request reason<textarea name="reason" required maxLength={1000}/></label><button className="button" disabled={busy}>Request protected change</button></form>{r.data.requests.map(x=><p key={x.id}>{x.state} · {x.proposal.reason}{x.decisionReason?` · ${x.decisionReason}`:''}</p>)}</Panel>}</>}
 {tab==='password'&&<Panel title="Change password" note="Use 12 to 128 characters. This ends all sessions; sign in with the new password afterwards. If MFA is enabled, use your authenticator after signing back in and generate new recovery codes."><form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/account/password',{password:f.get('password'),newPassword:f.get('newPassword'),code:f.get('code')||null},'POST',true);}}><Proof mfa={r.data.mfaEnabled}/><label>New password<input type="password" name="newPassword" required minLength={12} maxLength={128} autoComplete="new-password"/></label><button className="button button-primary" disabled={busy}>Change password</button></form></Panel>}
 {tab==='mfa'&&<Panel title="Two-factor authentication" note={r.data.mfaEnabled?'Enabled. Use a fresh six-digit code or an unused recovery code for security changes.':'Use an authenticator app with time-based six-digit codes.'}>{enrol?<><p>Enter this secret in your authenticator app:</p><code>{enrol.secret}</code><label>Authenticator setup URI<input aria-label="Authenticator setup URI" readOnly value={enrol.otpauthUri}/></label><p>Expires {new Date(enrol.expiresAt).toLocaleString()}.</p><form className="task-form" onSubmit={e=>{e.preventDefault();void act(`/account/mfa/enrolments/${enrol.enrolmentId}/confirm`,{code:new FormData(e.currentTarget).get('code')});}}><label>Authenticator code<input name="code" inputMode="numeric" pattern="[0-9]{6}" required maxLength={6} autoComplete="one-time-code"/></label><button className="button button-primary" disabled={busy}>Confirm and enable MFA</button></form><button className="button" disabled={busy} onClick={async()=>{const result=await act(`/account/mfa/enrolments/${enrol.enrolmentId}/cancel`,{});if(result)setEnrol(undefined);}}>Cancel enrolment</button></>:!r.data.mfaEnabled?<form className="task-form" onSubmit={async e=>{e.preventDefault();const password=new FormData(e.currentTarget).get('password');setBusy(true);setError('');try{setEnrol(await accountCommand<Enrolment>('/account/mfa/enrolments',{password,code:null}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Proof mfa={false}/><button className="button button-primary" disabled={busy}>Set up authenticator</button></form>:<form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),disable=f.get('action')==='disable';void act(disable?'/account/mfa/disable':'/account/mfa/recovery-codes',{password:f.get('password'),code:f.get('code')},'POST',disable);}}><Proof mfa/><label>Security action<select name="action"><option value="replace">Replace recovery codes</option><option value="disable">Disable MFA and end sessions</option></select></label><button className="button" disabled={busy}>Apply MFA security action</button></form>}</Panel>}
 {tab==='sessions'&&<><Panel title="Active sessions" note="Revocation takes effect on the next API request. Resuming an account cannot revive revoked sessions.">{r.data.sessions.map(x=><article className="task-form" key={x.id}><h3>{x.deviceLabel}{x.current?' · This session':''}</h3><p>Signed in {new Date(x.createdAt).toLocaleString()} · last seen {new Date(x.lastSeenAt).toLocaleString()} · expires {new Date(x.expiresAt).toLocaleString()}.</p><button className="button" disabled={busy} onClick={()=>void act(`/account/sessions/${x.id}/revoke`,{reason:'Account owner revoked session'},'POST',x.current)}>Revoke {x.current?'this':'selected'} session</button></article>)}<button className="button" disabled={busy} onClick={()=>void act('/account/sessions/revoke-others',{reason:'Account owner revoked other sessions'})}>Revoke all other sessions</button></Panel><Panel title="Report unrecognised activity"><form className="task-form" onSubmit={e=>{e.preventDefault();void act('/account/security-reports',{reason:new FormData(e.currentTarget).get('reason')});}}><label>Activity description<textarea name="reason" required maxLength={1000}/></label><p>Describe what you noticed. Do not include passwords or security codes. Reports are saved for you and security administrators.</p><button className="button" disabled={busy}>Save security report</button></form>{r.data.reports.map(x=><p key={x.id}>{new Date(x.occurredAt).toLocaleString()} · {x.reason}</p>)}</Panel></>}
 </>}</>;
}
function Proof({mfa}:{mfa:boolean}){return <><label>Current password<input name="password" type="password" required maxLength={1024} autoComplete="current-password"/></label>{mfa&&<label>Authenticator or recovery code<input name="code" required maxLength={100} autoComplete="one-time-code"/></label>}</>;}
