'use client';
import type {ReportDefinition as Definition,ReportFilters as Filters,ReportResult as Result,SavedReport as Saved,RecentReport as Recent,ReportPreferences as Preferences} from '../../../contracts/generated/reporting';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {csrfToken} from '../lib/auth';
import {DataTable,EmptyState,Panel,Status} from './primitives';
type Options={products:{code:string;name:string}[];agencies:{id:string;name:string}[];providers:{id:string;name:string}[];underwriters:{id:string;name:string}[]};
const categories=[['underwriting','Underwriting'],['portfolio','Policy portfolio'],['renewal','Renewals'],['finance','Finance'],['agency','Agency performance'],['compliance-exceptions','Compliance & exceptions']];
function range(months=3){const to=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const d=new Date(to+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()-months);return {from:d.toISOString().slice(0,10),to};}
function reportRange(code?:string,months=3){const dates=range(months);if(code==='earned-premium'){const end=new Date(dates.to.slice(0,7)+'-01T12:00:00Z');end.setUTCDate(0);dates.to=end.toISOString().slice(0,10);dates.from=dates.from.slice(0,7)+'-01';}return dates;}
function display(value:string|null|undefined,unit:string){if(value==null)return '—';const n=Number(value);return unit==='GBP'?n.toLocaleString('en-GB',{style:'currency',currency:'GBP'}):unit==='percent'?`${n.toLocaleString('en-GB',{maximumFractionDigits:2})}%`:n.toLocaleString('en-GB',{maximumFractionDigits:2})+(unit==='hours'?' h':'');}
export function ReportingWorkspace({reportId}:{reportId?:string}){
 const [definitions,setDefinitions]=useState<Definition[]|null>(null),[selected,setSelected]=useState(reportId??''),[category,setCategory]=useState('all'),[search,setSearch]=useState('');
 const [options,setOptions]=useState<Options|null>(null),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dates,setDates]=useState(()=>range());
 const [preferences,setPreferences]=useState<Preferences>({version:0,favourites:[],recent:[]}),[name,setName]=useState(''),[savedId,setSavedId]=useState(''),[preset,setPreset]=useState<Filters|null>(null),[formVersion,setFormVersion]=useState(0);
 const definition=definitions?.find(d=>d.id===selected);
 useEffect(()=>{const c=new AbortController();fetch('/api/v1/reports',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Report library could not be loaded.');return r.json();}).then(value=>{setDefinitions(value);if(reportId){const current=value.find((d:Definition)=>d.id===reportId);setDates(reportRange(current?.code));}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[reportId]);
 useEffect(()=>{const c=new AbortController();fetch('/api/v1/reports/preferences',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Saved reports could not be loaded.');return r.json();}).then(setPreferences).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();fetch('/api/v1/reports/'+selected+'/options',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Report filters are unavailable for your current role.');return r.json();}).then(value=>{if(!c.signal.aborted)setOptions(value);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[selected,formVersion]);
 function choose(id:string){setSelected(id);setOptions(null);setResult(null);setError('');setDates(reportRange(definitions?.find(d=>d.id===id)?.code));setPreset(null);setSavedId('');setName('');setFormVersion(v=>v+1);window.history.replaceState(null,'','/reporting?reportId='+id);}
 async function run(filters:Filters){setError('');setResult(null);setBusy(true);try{const response=await fetch('/api/v1/reports/'+selected+'/run',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':await csrfToken()},body:JSON.stringify(filters)});if(!response.ok){const body=await response.json().catch(()=>({}));throw Error(response.status===422?'This report exceeds 10,000 source rows. Narrow the dates or filters.':response.status===403?'Your current role cannot run this report.':String(body.code??body.title??'Check the date range and applicable filters.'));}setResult(await response.json());await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function refresh(){const response=await fetch('/api/v1/reports/preferences');if(!response.ok)throw Error('Saved reports could not be refreshed.');setPreferences(await response.json());}
 async function mutation(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function check(response:Response){if(!response.ok){const body=await response.json().catch(()=>({}));if(response.status===412)await refresh();throw Error(response.status===412?'Saved reports changed. Review the refreshed list and try again.':String(body.code??body.title??'Report action failed.'));}return response;}
 function recall(item:Saved|Recent){choose(item.reportId);setPreset(item.filters);setDates({from:item.filters.from,to:item.filters.to});setSavedId('id' in item?item.id:'');setName('name' in item?item.name:'');}
 async function save(){if(!result)return;await mutation(async()=>{const response=await check(await fetch('/api/v1/reports/favourites'+(savedId?'/'+savedId:''),{method:savedId?'PUT':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':await csrfToken()},body:JSON.stringify({version:preferences.version,reportId:result.reportId,name,filters:result.filters})}));setSavedId((await response.json()).id);await refresh();});}
 async function remove(id:string){await mutation(async()=>{await check(await fetch('/api/v1/reports/favourites/'+id+'?version='+preferences.version,{method:'DELETE',headers:{'X-CSRF-Token':await csrfToken()}}));if(savedId===id)setSavedId('');await refresh();});}
 async function download(){if(!result||!definition)return;await mutation(async()=>{const response=await check(await fetch('/api/v1/reports/'+result.reportId+'/export',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':await csrfToken()},body:JSON.stringify({filters:result.filters,format:'csv'})}));const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download=definition.code+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 return <><div className="page-heading"><div><h1>{definition?.title??'Reporting'}</h1><p>Reports respect your role and agency visibility.</p></div></div>
 <nav className="client-record-tabs" aria-label="Reporting sections"><button className="quote-tab" aria-current={!definition?'page':undefined} disabled={busy} onClick={()=>choose('')}>Report library</button>{definition?<button className="quote-tab" aria-current="page" disabled={busy}>{definition.title}</button>:definitions?.find(item=>item.code==='underwriting')&&<button className="quote-tab" disabled={busy} onClick={()=>choose(definitions!.find(item=>item.code==='underwriting')!.id)}>Underwriting performance</button>}</nav>
 <div hidden={!!definition}><Panel title="Report categories"><div className="report-library">{categories.map(([code,label])=><button className={'report-card'+(category===code?' selected':'')} key={code} aria-pressed={category===code} disabled={busy} onClick={()=>setCategory(code)}><strong>{label}</strong><span>{definitions?.filter(item=>item.category===code).length??0} reports available</span></button>)}</div></Panel>
 <Panel title="Your reports" note="Favourites save filters. Recent runs record the time and row count, not a frozen result. Reruns and CSV exports read current data and permissions."><div className="report-filter-grid"><div><h3>Favourites</h3>{preferences.favourites.length===0?<p>No favourites saved yet.</p>:preferences.favourites.map(item=><div key={item.id}><button className="button" disabled={busy} onClick={()=>recall(item)}>{item.name}</button> <button className="button" disabled={busy} aria-label={'Remove '+item.name} onClick={()=>remove(item.id)}>Remove</button></div>)}</div><div><h3>Recent runs</h3>{preferences.recent.length===0?<p>No recent runs.</p>:preferences.recent.slice(0,5).map((item,i)=><p key={i}><button className="button" disabled={busy} onClick={()=>recall(item)}>{definitions?.find(d=>d.id===item.reportId)?.title??'Report'}</button><small> {new Date(item.ranAt).toLocaleString('en-GB')} · {item.totalRows} rows at run time</small></p>)}</div></div></Panel>
 <Panel title="Report library" note="Counts reflect reports available to your current role."><div className="report-filter-grid"><label>Find a report<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or description"/></label><label>Report category<select aria-label="Report category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories ({definitions?.length??0})</option>{categories.map(([code,label])=><option key={code} value={code}>{label} ({definitions?.filter(d=>d.category===code).length??0})</option>)}</select></label></div>
 <div className="report-library">{definitions?.filter(d=>(category==='all'||d.category===category)&&(d.title+' '+d.description).toLowerCase().includes(search.toLowerCase())).map(d=><button key={d.id} className={'report-card'+(selected===d.id?' selected':'')} onClick={()=>choose(d.id)} disabled={busy} aria-pressed={selected===d.id}><strong>{d.title}</strong><span>{d.description}</span><small>{d.measures.length} defined measures →</small></button>)}</div>{definitions?.length===0&&<EmptyState title="No reports for your current role">Report access follows the existing business permissions.</EmptyState>}</Panel>
 </div>{error&&<p role="alert">{error}</p>}
 {definition&&<button className="button" disabled={busy} onClick={()=>choose('')}>Back to reports</button>}
 {definition&&!options&&<p role="status">Loading report filters…</p>}
 {definition&&options&&<Panel title={definition.title} note={definition.description}><form key={definition.id+formVersion} className="report-filter-grid" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const filters={...dates,basis:String(form.get('basis'))} as Filters;for(const key of definition.filters){const value=form.get(key);if(value)(filters as unknown as Record<string,string>)[key]=String(value);}void run(filters);}}>
 <label>Period<select aria-label="Period" defaultValue={preset?"custom":"3"} onChange={e=>{if(e.target.value==='custom')return;const next=reportRange(definition.code,Number(e.target.value)||0);if(e.target.value==='year')next.from=next.to.slice(0,4)+'-01-01';setDates(next);}}><option value="3">Last 3 months</option><option value="6">Last 6 months</option><option value="year">Year to date</option><option value="custom">Custom range</option></select></label>
 <label>From (inclusive)<input type="date" required value={dates.from} onChange={e=>setDates({...dates,from:e.target.value})}/></label><label>To (inclusive)<input type="date" required value={dates.to} onChange={e=>setDates({...dates,to:e.target.value})}/></label>
 <label>Date basis<select aria-label="Date basis" name="basis" defaultValue={preset?.basis??definition.defaultBasis}>{definition.bases.map(b=><option key={b}>{b}</option>)}</select></label>
 {definition.filters.includes('productCode')&&<label>Product<select aria-label="Product" name="productCode" defaultValue={preset?.productCode??''}><option value="">All products</option>{options?.products.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label>}
 {(['agencyId','providerId','underwriterId'] as const).filter(k=>definition.filters.includes(k)).map(k=>{const label=k==='agencyId'?'Agency':k==='providerId'?'Insurer':'Assigned underwriter';const rows=k==='agencyId'?options?.agencies:k==='providerId'?options?.providers:options?.underwriters;return <label key={k}>{label}<select aria-label={label} name={k} defaultValue={preset?.[k]??''}><option value="">All</option>{rows?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;})}
 <button className="button button-primary" disabled={busy||options===null}>{busy?'Running…':'Run report'}</button></form><p className="panel-footer">Dates use the Europe/London calendar. Every run reads current saved data; at most 10,000 source rows. Empty denominators display —.</p></Panel>}
 {result&&definition&&<><Panel title="Save or export this run" note="The CSV contains all matching source rows (maximum 10,000), using the applied filters below."><div className="report-filter-grid"><label>Favourite name<input maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><button className="button" disabled={busy||!name.trim()} onClick={save}>{savedId?'Update favourite':'Save favourite'}</button><button className="button button-primary" disabled={busy} onClick={download}>Export CSV</button></div><p>{result.filters.from} to {result.filters.to} · {result.filters.basis} basis</p></Panel><Panel title="Report measures" note={`Generated ${new Date(result.generatedAt).toLocaleString('en-GB',{timeZone:'Europe/London'})} London · ${result.totalRows} source rows`}><div className="kpi-grid">{definition.measures.map(m=>{const value=result.measures.find(v=>v.code===m.code);return <div className="kpi" key={m.code}><p>{m.label}</p><strong>{display(value?.value,m.unit)}</strong><span>{m.definition}{value?.denominator!=null?` Denominator: ${value.denominator}.`:''}</span></div>;})}</div></Panel>
 {result.groups.length>0&&<Panel title="Agency, month and product breakdown"><DataTable caption="Report groups" columns={['Agency','Month','Product',...definition.measures.map(m=>m.label)]}>{result.groups.map((g,i)=><tr key={i}><td>{options?.agencies.find(a=>a.id===g.agencyId)?.name??g.agencyId}</td><td>{g.month}</td><td>{g.productCode??'All products'}</td>{definition.measures.map(m=><td key={m.code}>{display(g.measures.find(v=>v.code===m.code)?.value,m.unit)}</td>)}</tr>)}</DataTable></Panel>}
 <Panel title="Underlying records" note="Source IDs identify the saved revision, term, transaction or posting. Each page reruns the same filters against current data.">{result.rows.length?<DataTable caption="Report source records" columns={['Reference','Record','Product','Status','Basis date',...definition.measures.map(m=>m.label)]}>{result.rows.map((r,i)=><tr key={(r.sourceId??r.recordId)+'-'+i}><td><Link href={r.href} prefetch={false}>{r.reference}</Link><small className="report-source">Source: {r.sourceId??r.recordId}</small></td><td>{r.label}</td><td>{r.productCode??'—'}</td><td><Status>{r.state}</Status></td><td>{r.basisDate??new Date(r.at).toLocaleDateString('en-GB',{timeZone:'Europe/London'})}</td>{definition.measures.map(m=><td key={m.code}>{display(r.values[m.code],m.unit)}</td>)}</tr>)}</DataTable>:<EmptyState title="No matching records">The saved data has no records for this cohort and filter range.</EmptyState>}{result.nextOffset!=null&&<button className="button" disabled={busy} onClick={()=>run({...result.filters,offset:result.nextOffset!})}>Next 50 records</button>}</Panel></>}
 </>;
}
