'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {csrfToken} from '../lib/auth';
import {DataTable,EmptyState,Panel,Status} from './primitives';
type Measure={code:string;label:string;definition:string;unit:string};
type Definition={id:string;code:string;category:string;title:string;description:string;defaultBasis:string;bases:string[];filters:string[];measures:Measure[]};
type Filters={from:string;to:string;basis:string;agencyId?:string;providerId?:string;productCode?:string;underwriterId?:string;offset?:number};
type Value={code:string;value:string|null;denominator:string|null};
type Row={recordId:string;kind:string;reference:string;label:string;state:string;href:string;sourceId:string|null;agencyId:string|null;productCode:string|null;at:string;values:Record<string,string|null>};
type Result={reportId:string;generatedAt:string;filters:Filters;definition:string;totalRows:number;measures:Value[];rows:Row[];nextOffset:number|null;groups:{agencyId:string;month:string;productCode:string;measures:Value[]}[]};
type Options={products:{code:string;name:string}[];agencies:{id:string;name:string}[];providers:{id:string;name:string}[];underwriters:{id:string;name:string}[]};
const categories=[['underwriting','Underwriting'],['portfolio','Policy portfolio'],['renewal','Renewals'],['finance','Finance'],['agency','Agency performance'],['compliance-exceptions','Compliance & exceptions']];
function range(months=3){const to=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const d=new Date(to+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()-months);return {from:d.toISOString().slice(0,10),to};}
function display(value:string|null|undefined,unit:string){if(value==null)return '—';const n=Number(value);return unit==='GBP'?n.toLocaleString('en-GB',{style:'currency',currency:'GBP'}):unit==='percent'?`${n.toLocaleString('en-GB',{maximumFractionDigits:2})}%`:n.toLocaleString('en-GB',{maximumFractionDigits:2})+(unit==='hours'?' h':'');}
export function ReportingWorkspace({reportId}:{reportId?:string}){
 const [definitions,setDefinitions]=useState<Definition[]|null>(null),[selected,setSelected]=useState(reportId??''),[category,setCategory]=useState('all'),[search,setSearch]=useState('');
 const [options,setOptions]=useState<Options|null>(null),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dates,setDates]=useState(()=>range());
 const definition=definitions?.find(d=>d.id===selected);
 useEffect(()=>{const c=new AbortController();fetch('/api/v1/reports',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Report library could not be loaded.');return r.json();}).then(setDefinitions).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();fetch('/api/v1/reports/'+selected+'/options',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Report filters are unavailable for your current role.');return r.json();}).then(value=>{if(!c.signal.aborted)setOptions(value);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[selected]);
 function choose(id:string){setSelected(id);setOptions(null);setResult(null);setError('');setDates(range());window.history.replaceState(null,'','/reporting?reportId='+id);}
 async function run(filters:Filters){setError('');setResult(null);setBusy(true);try{const response=await fetch('/api/v1/reports/'+selected+'/run',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':await csrfToken()},body:JSON.stringify(filters)});if(!response.ok){const body=await response.json().catch(()=>({}));throw Error(response.status===422?'This report exceeds 10,000 source rows. Narrow the dates or filters.':response.status===403?'Your current role cannot run this report.':String(body.code??body.title??'Check the date range and applicable filters.'));}setResult(await response.json());}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-heading"><div><h1>Reporting</h1><p>Saved business records, defined measures and traceable results.</p></div></div>
 <Panel title="Report library" note="Counts reflect reports available to your current role."><div className="report-filter-grid"><label>Find a report<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or description"/></label><label>Report category<select aria-label="Report category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories ({definitions?.length??0})</option>{categories.map(([code,label])=><option key={code} value={code}>{label} ({definitions?.filter(d=>d.category===code).length??0})</option>)}</select></label></div>
 <div className="report-library">{definitions?.filter(d=>(category==='all'||d.category===category)&&(d.title+' '+d.description).toLowerCase().includes(search.toLowerCase())).map(d=><button key={d.id} className={'report-card'+(selected===d.id?' selected':'')} onClick={()=>choose(d.id)} disabled={busy} aria-pressed={selected===d.id}><strong>{d.title}</strong><span>{d.description}</span><small>{d.measures.length} defined measures →</small></button>)}</div>{definitions?.length===0&&<EmptyState title="No reports for your current role">Report access follows the existing business permissions.</EmptyState>}</Panel>
 {error&&<p role="alert">{error}</p>}
 {definition&&<Panel title={definition.title} note={definition.description}><form key={definition.id} className="report-filter-grid" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const filters={...dates,basis:String(form.get('basis'))} as Filters;for(const key of definition.filters){const value=form.get(key);if(value)(filters as unknown as Record<string,string>)[key]=String(value);}void run(filters);}}>
 <label>Period<select aria-label="Period" defaultValue="3" onChange={e=>{if(e.target.value==='custom')return;const next=range(Number(e.target.value)||0);if(e.target.value==='year')next.from=next.to.slice(0,4)+'-01-01';setDates(next);}}><option value="3">Last 3 months</option><option value="6">Last 6 months</option><option value="year">Year to date</option><option value="custom">Custom range</option></select></label>
 <label>From (inclusive)<input type="date" required value={dates.from} onChange={e=>setDates({...dates,from:e.target.value})}/></label><label>To (inclusive)<input type="date" required value={dates.to} onChange={e=>setDates({...dates,to:e.target.value})}/></label>
 <label>Date basis<select aria-label="Date basis" name="basis" defaultValue={definition.defaultBasis}>{definition.bases.map(b=><option key={b}>{b}</option>)}</select></label>
 {definition.filters.includes('productCode')&&<label>Product<select aria-label="Product" name="productCode"><option value="">All products</option>{options?.products.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label>}
 {(['agencyId','providerId','underwriterId'] as const).filter(k=>definition.filters.includes(k)).map(k=>{const label=k==='agencyId'?'Agency':k==='providerId'?'Insurer':'Assigned underwriter';const rows=k==='agencyId'?options?.agencies:k==='providerId'?options?.providers:options?.underwriters;return <label key={k}>{label}<select aria-label={label} name={k}><option value="">All</option>{rows?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;})}
 <button className="button button-primary" disabled={busy||options===null}>{busy?'Running…':'Run report'}</button></form><p className="panel-footer">Dates use the Europe/London calendar. Every run reads current saved data; at most 10,000 source rows. Empty denominators display —.</p></Panel>}
 {result&&definition&&<><Panel title="Report measures" note={`Generated ${new Date(result.generatedAt).toLocaleString('en-GB',{timeZone:'Europe/London'})} London · ${result.totalRows} source rows`}><div className="kpi-grid">{definition.measures.map(m=>{const value=result.measures.find(v=>v.code===m.code);return <div className="kpi" key={m.code}><p>{m.label}</p><strong>{display(value?.value,m.unit)}</strong><span>{m.definition}{value?.denominator!=null?` Denominator: ${value.denominator}.`:''}</span></div>;})}</div></Panel>
 {result.groups.length>0&&<Panel title="Agency, month and product breakdown"><DataTable caption="Report groups" columns={['Agency','Month','Product',...definition.measures.map(m=>m.label)]}>{result.groups.map((g,i)=><tr key={i}><td>{options?.agencies.find(a=>a.id===g.agencyId)?.name??g.agencyId}</td><td>{g.month}</td><td>{g.productCode}</td>{definition.measures.map(m=><td key={m.code}>{display(g.measures.find(v=>v.code===m.code)?.value,m.unit)}</td>)}</tr>)}</DataTable></Panel>}
 <Panel title="Underlying records" note="Source IDs identify the saved revision, term, transaction or posting. Each page reruns the same filters against current data.">{result.rows.length?<DataTable caption="Report source records" columns={['Reference','Record','Product','Status','Basis date',...definition.measures.map(m=>m.label)]}>{result.rows.map((r,i)=><tr key={r.sourceId??r.recordId+'-'+i}><td><Link href={r.href} prefetch={false}>{r.reference}</Link><small className="report-source">Source: {r.sourceId??r.recordId}</small></td><td>{r.label}</td><td>{r.productCode??'—'}</td><td><Status>{r.state}</Status></td><td>{new Date(r.at).toLocaleDateString('en-GB',{timeZone:'Europe/London'})}</td>{definition.measures.map(m=><td key={m.code}>{display(r.values[m.code],m.unit)}</td>)}</tr>)}</DataTable>:<EmptyState title="No matching records">The saved data has no records for this cohort and filter range.</EmptyState>}{result.nextOffset!=null&&<button className="button" disabled={busy} onClick={()=>run({...result.filters,offset:result.nextOffset!})}>Next 50 records</button>}</Panel></>}
 </>;
}
