'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { DataTable, EmptyState, Panel, Status } from '../primitives';
import type { AgencySummary } from '../../lib/agencies';
import { clientDate, type Page } from '../../lib/clients';
import { LoadFeedback, useAgencyResource } from './shared';

export function AgencyList({canWrite,query}: {canWrite: boolean; query: Record<string,string>}) {
  const router = useRouter(); const params = new URLSearchParams(query); params.set('pageSize','15');
  const resource = useAgencyResource<Page<AgencySummary>>(`/api/v1/agencies?${params}`);
  const managers = useAgencyResource<Page<{id: string; displayName: string}>>('/api/v1/agency-relationship-managers?pageSize=100');
  const kpis = useAgencyResource<{active: number; onboarding: number; suspended: number; brokerUsers:number; invitedUsers:number; openActions:number; pendingStateRequests:number; pendingTermsRequests:number; pendingPermissionRequests:number; dueFollowUps:number; asOfDate:string}>('/api/v1/agencies/kpis');
  const change = (next: URLSearchParams) => {next.delete('pageSize');router.push(`/agents?${next}`);};
  return <><div className="page-heading"><div><h1>Agents</h1><p>Wholesale agencies and onboarding</p></div>{canWrite && <Link className="button button-primary" href="/agents/new">Create agency</Link>}</div>
    <div className="agency-kpis">{[['Active agencies',kpis.data?.active],['Broker users',kpis.data?.brokerUsers],['Suspended',kpis.data?.suspended],['Open actions',kpis.data?.openActions]].map(([label,value]) => <div className="panel" key={String(label)}><span>{label}</span><strong>{value ?? '…'}</strong>{label==='Broker users'&&kpis.data&&<small>{kpis.data.invitedUsers} awaiting acceptance, including staged users; total includes inactive users</small>}{label==='Open actions'&&kpis.data&&<small>{kpis.data.pendingStateRequests} state, {kpis.data.pendingTermsRequests} terms and {kpis.data.pendingPermissionRequests} access requests awaiting a decision</small>}</div>)}</div>{kpis.data&&<p className="client-help">All agencies · {kpis.data.dueFollowUps} recorded follow-up obligations due by {clientDate(kpis.data.asOfDate)}. Follow-up completion tracking is not available yet.</p>}{kpis.error && <LoadFeedback error={kpis.error} retry={kpis.refresh} />}
    <Panel title="Agency directory"><form key={JSON.stringify(query)} className="operations-toolbar" onSubmit={event => {event.preventDefault();const next = new URLSearchParams();for(const [key,value] of new FormData(event.currentTarget)) if(String(value).trim()) next.set(key,String(value).trim());change(next);}}>
      <label>Search agencies<input name="q" type="search" defaultValue={query.q ?? ''} maxLength={200} placeholder="Agency name or reference" /></label>
      <label>Status<select name="state" defaultValue={query.state ?? ''}><option value="">All statuses</option><option value="draft">Onboarding</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="abandoned">Abandoned</option></select></label>
      <label>Relationship manager<select name="relationshipManagerId" defaultValue={query.relationshipManagerId ?? ''}><option value="">All relationship managers</option>{managers.data?.items.map(x => <option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><button className="button" type="submit">Search</button><Link className="button" href="/agents">Clear filters</Link>
    </form>{managers.error && <LoadFeedback error={managers.error} retry={managers.refresh} />}
    {!resource.data ? <LoadFeedback error={resource.error} retry={resource.refresh} /> : !resource.data.items.length ? <EmptyState title="No agencies match">Clear the filters or create an agency draft.</EmptyState> : <DataTable caption="Agency directory" columns={['Agency','Reference','Status','Main contact','Relationship manager','Users','Products','Open actions','Last activity','Open']}>
      {resource.data.items.map(x => <tr key={x.id}><td><Link className="client-name" href={`/agents/${x.id}`}>{x.legalName ?? 'Unnamed agency draft'}</Link></td><td>{x.reference}</td><td><Status tone={x.state === 'active' ? 'success' : 'muted'}>{x.state === 'draft' ? 'Onboarding' : x.state}</Status></td><td>{x.mainContactName ?? 'Not entered'}</td><td>{x.relationshipManagerName ?? 'Not assigned'}</td><td>{x.userCount}<small className="client-help"> / {x.invitedUserCount} awaiting acceptance</small></td><td>{x.productCodes.length ? x.productCodes.map(x => x.replaceAll('-',' ')).join(' · ') : 'No products selected'}</td><td><div>{x.openActionCount} pending</div><small className="client-help">{x.dueFollowUpCount} recorded follow-ups due</small></td><td>{x.lastActivityAt ? clientDate(x.lastActivityAt,true) : 'No activity recorded'}</td><td><Link href={canWrite && x.state === 'draft' ? `/agents/${x.id}/onboarding` : `/agents/${x.id}`}>{canWrite && x.state === 'draft' ? 'Resume onboarding' : 'Open agency'}</Link></td></tr>)}
    </DataTable>}<div className="panel-footer operations-actions"><span>{resource.data?.totalCount ?? '…'} agencies</span><button className="button" disabled={!query.cursor} onClick={() => {const next = new URLSearchParams(query);next.delete('cursor');change(next);}}>First page</button><button className="button" disabled={!resource.data?.nextCursor} onClick={() => {const next = new URLSearchParams(query);next.set('cursor',resource.data!.nextCursor!);change(next);}}>Next page</button></div></Panel>
  </>;
}
