'use client';
import {useEffect,useRef,useState} from 'react';
import {Panel} from '../primitives';
import {agencyFetch,AgencyError,flattenDraft,visibleTermsFields,agreedTermsPayload,type AgencyDraft,type CatalogProduct,type TermsProductInput} from '../../lib/agencies';
import {agencyFields} from '../../lib/agency-fields';
import type {AgencyTermsVersion} from '../../lib/agency-terms';
import type {Page} from '../../lib/clients';
import {csrfToken} from '../../lib/auth';

export function AgencyTermsProposal({id,onSaved}:{id:string;onSaved:()=>void}) {
  const [loaded,setLoaded]=useState<{etag:string;latest:string;catalog:CatalogProduct[]}>();
  const [values,setValues]=useState<Record<string,string>>({});const [products,setProducts]=useState<TermsProductInput[]>([]);const [reason,setReason]=useState('');
  const [busy,setBusy]=useState(false);const [uncertain,setUncertain]=useState(false);const [stale,setStale]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const dialog=useRef<HTMLDialogElement>(null);const first=useRef<HTMLInputElement>(null);const trigger=useRef<HTMLButtonElement>(null);const lock=useRef(false);
  const command=useRef<{key:string;etag:string;body:string}>(undefined);
  useEffect(()=>{if(loaded){dialog.current?.showModal();first.current?.focus();}},[loaded]);
  useEffect(()=>{if(!loaded)return;const unload=(event:BeforeUnloadEvent)=>event.preventDefault();const navigate=(event:MouseEvent)=>{if((event.target as Element).closest?.('a[href]')){event.preventDefault();event.stopPropagation();}};window.addEventListener('beforeunload',unload);document.addEventListener('click',navigate,true);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',navigate,true);};},[loaded]);
  function close(){if(lock.current||uncertain)return;dialog.current?.close();setLoaded(undefined);command.current=undefined;requestAnimationFrame(()=>trigger.current?.focus());}
  async function begin(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');
    try{const [agency,terms,catalog]=await Promise.all([agencyFetch<AgencyDraft>(`/api/v1/agencies/${id}`),agencyFetch<Page<AgencyTermsVersion>>(`/api/v1/agencies/${id}/terms?pageSize=1`),agencyFetch<Page<CatalogProduct>>('/api/v1/agency-product-catalog')]);
      if(!['active','suspended'].includes(agency.data.state)||!terms.data.items.length)throw Error('The agency must have approved initial terms before proposing a change.');
      if(!agency.etag||agency.etag!==terms.etag)throw Error('The agency changed while loading. Open the proposal again to load a consistent version.');
      const latest=terms.data.items[0];setValues(flattenDraft({commercialTerms:latest.commercialTerms,settlement:latest.settlement,paymentTermsDays:latest.paymentTermsDays,creditLimit:latest.creditLimit}));
      setProducts(latest.products.map(x=>({productVersionId:x.productVersionId,effectiveFrom:x.effectiveFrom,commission:(x.brokerCommissionBasisPoints/100).toFixed(2)})));setReason('');setStale(false);setUncertain(false);setLoaded({etag:agency.etag,latest:latest.effectiveFrom,catalog:catalog.data.items});
    }catch(failure){setError((failure as Error).message);}finally{lock.current=false;setBusy(false);}}
  async function submit(){if(lock.current||!loaded||stale)return;if(!uncertain){try{command.current={key:crypto.randomUUID(),etag:loaded.etag,body:JSON.stringify(agreedTermsPayload(values,agencyFields,products,reason,loaded.latest))};}catch(failure){setError((failure as Error).message);return;}}
    lock.current=true;setBusy(true);setError('');const pending=command.current!;
    try{await agencyFetch(`/api/v1/agencies/${id}/terms-requests`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':await csrfToken(),'Idempotency-Key':pending.key,'If-Match':pending.etag},body:pending.body});}
    catch(failure){const unknown=!(failure instanceof AgencyError)||failure.status>=500;setUncertain(unknown);setStale(!unknown&&failure instanceof AgencyError&&[409,412,428].includes(failure.status));setError(unknown?'The result is uncertain. Retry the same proposal to recover it.':failure instanceof AgencyError&&[409,412,428].includes(failure.status)?'The agency changed or already has a pending proposal. Your entries are retained here. Cancel and review the current agency before starting a new proposal.':(failure as Error).message);lock.current=false;setBusy(false);return;}
    setUncertain(false);lock.current=false;setBusy(false);dialog.current?.close();setLoaded(undefined);command.current=undefined;setNotice('Terms proposal saved. Current terms remain in force until independent approval and the agreed effective date.');requestAnimationFrame(()=>trigger.current?.focus());onSaved();
  }
  function edit(path:string,value:string){setValues(x=>({...x,[path]:value}));}
  return <Panel title="Change agreed terms"><p className="match-copy">Propose a complete replacement version based on the latest approved terms, including scheduled changes. Another administrator must approve it.</p><button ref={trigger} className="button" disabled={busy||!!loaded} onClick={()=>void begin()}>Propose terms change</button>
    <dialog ref={dialog} className="agency-dialog agency-terms-dialog" aria-labelledby="agency-terms-proposal-title" onCancel={event=>{event.preventDefault();close();}}><form noValidate onSubmit={event=>{event.preventDefault();void submit();}}><h2 id="agency-terms-proposal-title">Propose agreed terms</h2><p className="match-copy">Latest approved effective date: {loaded?.latest}. Enter a later date; past dates are not allowed. Review all products and account settings.</p><fieldset disabled={busy||uncertain}><legend className="sr-only">Complete proposed terms</legend>
      <label>Reason<input ref={first} required maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label>
      <div className="client-field-grid">{visibleTermsFields(values,agencyFields).map(field=><label key={field.path}>{field.label}{field.options?<select aria-label={field.label} value={values[field.path]??''} onChange={event=>edit(field.path,event.target.value)}><option value="">Select…</option>{Object.entries(field.options).map(([label,value])=><option key={value} value={value}>{label}</option>)}</select>:<input required aria-label={field.label} type={field.type==='date'?'date':'text'} inputMode={['money','percent'].includes(field.type??'')?'decimal':undefined} value={values[field.path]??''} onChange={event=>edit(field.path,event.target.value)}/>}</label>)}</div>
      <h3>Products and commission</h3><p className="match-copy">At least one product must start on the terms effective date. Set each product date explicitly.</p>
      {loaded?.catalog.map(product=>{const row=products.find(x=>x.productVersionId===product.productVersionId);return <div className="agency-product" key={product.productVersionId}><label className="contact-check"><input type="checkbox" checked={!!row} onChange={event=>setProducts(x=>event.target.checked?[...x,{productVersionId:product.productVersionId,effectiveFrom:values['commercialTerms.effectiveFrom']??'',commission:''}]:x.filter(y=>y.productVersionId!==product.productVersionId))}/>{product.name}</label><p className="client-help">{product.capacityProviderName}{!product.distributionEligible?' · Currently unavailable for distribution':''}</p>{row&&<div className="client-field-grid"><label>Product effective from<input type="date" aria-label={`${product.name} effective from`} value={row.effectiveFrom} onChange={event=>setProducts(x=>x.map(y=>y===row?{...y,effectiveFrom:event.target.value}:y))}/></label><label>Broker commission (%)<input inputMode="decimal" aria-label={`${product.name} commission`} value={row.commission} onChange={event=>setProducts(x=>x.map(y=>y===row?{...y,commission:event.target.value}:y))}/></label></div>}</div>;})}
      {products.filter(x=>!loaded?.catalog.some(p=>p.productVersionId===x.productVersionId)).map(product=><div key={product.productVersionId}><p className="error-message">A previously agreed product is unavailable in the current catalogue. Remove it before submitting.</p><button type="button" className="button" onClick={()=>setProducts(x=>x.filter(p=>p!==product))}>Remove unavailable product</button></div>)}
    </fieldset>{error&&<p className="error-message" role="alert">{error}</p>}<div className="operations-actions"><button className="button button-primary" disabled={busy||stale}>{busy?'Saving…':uncertain?'Retry same proposal':'Submit for approval'}</button><button className="button secondary" type="button" disabled={busy||uncertain} onClick={close}>Cancel</button></div></form></dialog>{!loaded&&error&&<p className="error-message" role="alert">{error}</p>}<p className="match-copy" role="status">{notice}</p>
  </Panel>;
}
