using BackOffice.Application;
using BackOffice.Infrastructure.Quotes;
namespace BackOffice.Infrastructure.Reporting;
public sealed record ReportMeasure(string Code,string Label,string Definition,string Unit,string? Numerator=null,string? Denominator=null);
public sealed record ReportDefinition(Guid Id,string Code,string Category,string Title,string Description,string Capability,string DefaultBasis,string[] Bases,string[] Filters,ReportMeasure[] Measures);
public static class ReportCatalogue
{
 public static ReportMeasure M(string code,string label,string definition,string unit="count")=>new(code,label,definition,unit);
 public static readonly ReportMeasure[] QuoteMeasures=[M("count","Quotes","One current saved quote per quote-created cohort member."),M("bound","Bound","Cohort quotes with an issued new-business policy."),new("conversion","Conversion","Bound cohort quotes divided by all cohort quotes; unavailable for an empty cohort.","percent","bound","count"),M("referred","Referred","Cohort quotes with referrals in the current underwriting cycle."),M("declined","Declined","Cohort quotes currently declined."),M("premium","Bound GWP","Term premium from the first-issue pinned rating; servicing movements excluded.","GBP")];
 public static readonly ReportDefinition[] All=[
  D(11,"active-portfolio","portfolio","Active policy portfolio","One active policy at the end of the selected London date range, using known issued versions and excluding cancellations and expired terms.","policy-read","effective",["effective"],true,[M("count","Active policies","Distinct selected active policies overlapping the observation window.")]),
  D(1,"underwriting","underwriting","Underwriting performance","Quote-created cohort, current outcomes and pinned first-issue premium.","quote-read","processed",["processed"],true,QuoteMeasures),
  D(2,"portfolio","portfolio","Policy portfolio","Transactions in the selected effective or processed window; one row per issued transaction, with active-policy status at the report cutoff.","policy-read","effective",["effective","processed"],true,[M("count","Transactions","Issued transactions, never policy slices."),M("newBusiness","New business","Transactions of kind new-business."),M("cancelled","Cancellations","Issued cancellation transactions."),M("premium","Premium movement","Sealed transaction obligation premium, identical to the policy's authorised financial view.","GBP")]),
  D(3,"renewal-retention","renewal","Renewal retention","Expiring-term cohort; issued contiguous successor terms, saved lapse decisions and distinct invitation deliveries.","policy-read","effective",["effective"],true,[M("count","Expiring terms","Terms ending in the selected window."),M("renewed","Renewed","Expiring terms with an issued successor starting at expiry."),M("invited","Invited","Terms with a successfully completed renewal terms delivery."),M("lapsed","Lapsed","Terms with a retained lapse event."),new("retention","Retention","Renewed divided by eligible expired terms; future expiries are excluded from the denominator.","percent","renewedExpired","expired")]),
  D(4,"renewal-invitations","renewal","Renewal invitations due","Uncancelled terms in the configured invitation window, without a successful invitation, acceptance or issued successor.","policy-read","effective",["effective"],true,[M("count","Invitations due","Eligible future term ends due under the current saved renewal rule, without invitation or successor.")]),
  D(5,"finance","finance","Financial performance","Sealed written-premium movements, commissions, cash and debt movement; processing basis is the saved posting date.","finance-read","processed",["processed","effective"],false,[M("count","Movements","One row per sealed journal or separate finance posting."),M("premium","Written premium","Sealed obligation premium, including signed reversals.","GBP"),M("commission","Commission","Sealed obligation commission.","GBP"),M("cash","Cash movement","Saved cash deltas in the selected window.","GBP"),M("debt","Receivable movement","Invoice due plus separate debtor deltas in the window; this is movement, not closing balance.","GBP"),M("closingDebt","Closing receivable balance","All sealed invoices and saved debtor deltas through To, including opening sources before From.","GBP")]),
  D(6,"earned-premium","finance","Earned premium","Persisted earning slices for complete calendar months; includes closed accounting periods and original algorithm/source identities.","finance-read","effective",["effective"],false,[M("count","Earning slices","One saved source-component/month slice."),M("earned","Earned premium","Sum of stored earned pence; never recomputed using current product rules.","GBP")]),
  D(7,"agency-conversion","agency","Agency conversion league","Quote-created cohort ranked by agency conversion. Underlying quote rows retain the same filters.","quote-read","processed",["processed"],true,QuoteMeasures),
  D(8,"referral-turnaround","compliance-exceptions","Referral turnaround","Current-cycle referrals created in the window; latest saved decision time minus referral creation. Open referrals have no completed duration.","underwriting-read","processed",["processed"],true,[M("count","Referrals","One referral in its quote's current cycle."),M("decided","Decided","Referrals with a current latest decision."),new("turnaround","Average turnaround","Total hours to latest decision divided by decided referrals; empty denominators are unavailable.","hours","hours","decided")]),
  D(9,"compliance","compliance-exceptions","Compliance and exceptions","Recorded complaint flags and visible tasks with changed sources. These are flags and operational exceptions, not adjudicated complaint cases.","support-internal-read","processed",["processed"],false,[M("count","Recorded exceptions","Saved complaint flags or changed-source tasks created in the selected window.")]),
  D(10,"bordereau-reconciliation","finance","Bordereau reconciliation","Current saved batch versions and included members reconciled against their sealed source journals.","finance-read","processed",["processed"],false,[M("count","Included members","Members in current batch versions, excluding explicitly excluded members."),M("premium","Batch premium","Saved member premium.","GBP"),M("sourcePremium","Source premium","Premium of each member's sealed source obligation.","GBP"),M("difference","Difference","Saved member premium minus sealed source premium.","GBP")])
 ];
 private static ReportDefinition D(int n,string code,string category,string title,string description,string capability,string basis,string[] bases,bool underwriter,ReportMeasure[] measures)=>new(Guid.Parse($"12000000-0000-4000-8000-{n:000000000000}"),code,category,title,description,capability,basis,bases,underwriter?["agencyId","providerId","productCode","underwriterId"]:code is "compliance" or "finance"?["agencyId"]:["agencyId","providerId","productCode"],measures);
 public static ReportDefinition Get(Guid id)=>All.SingleOrDefault(x=>x.Id==id)??throw new QuoteOperationException(404,"report-not-found");
 public static ReportDefinition Authorize(ActorContext actor,Guid id){var d=Get(id);ReportingScope.Require(actor,d.Capability);return d;}
}
