<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/BackOffice.Domain/BackOffice.Domain.csproj" />
    <ProjectReference Include="../../src/BackOffice.Application/BackOffice.Application.csproj" />
    <ProjectReference Include="../../src/BackOffice.Infrastructure/BackOffice.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../../contracts/examples/quote-capture-*.json" LogicalName="QuoteExamples.%(Filename)%(Extension)" />
    <EmbeddedResource Include="../../../contracts/examples/underwriting-demo.json" LogicalName="UnderwritingExamples.Demo" />
    <EmbeddedResource Include="../../../contracts/examples/issued-*.json" LogicalName="PolicyExamples.%(Filename)%(Extension)" />
    <EmbeddedResource Include="../../../contracts/examples/commercial-combined-capture.json" LogicalName="CommercialExamples.Capture" />
    <EmbeddedResource Include="../../../contracts/examples/commercial-underwriting-demo.json" LogicalName="CommercialExamples.Underwriting" />
    <EmbeddedResource Include="../../../contracts/examples/commercial-combined-ready.json" LogicalName="CommercialExamples.Ready" />
  </ItemGroup>
</Project>
