'use client';
import {useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Panel,DataTable,EmptyState,Status} from '../primitives';
import {RecordHeader} from '../record-header';
import {clientFetch,ClientError,clientDate,uncertainFailure,type Client,type Relationship,type Page} from '../../lib/clients';
import {availableDecisions,decisionLabels,matchStates,ruleLabels,matchPayload,type MatchReview,type MatchOutcome,type MatchDecision,type MatchRequest} from '../../lib/matches';
import {csrfToken} from '../../lib/auth';
import {LoadFeedback,Paging,useClientResource} from './shared';

export function MatchWorkspace({matchId,tab,canDecide}:{matchId:string;tab:string;canDecide:boolean}){
  const resource=useClientResource<MatchReview>(`/api/v1/matches/${matchId}`);
  return <><div className="sr-only" role="status" aria-atomic="true">{resource.data?`Review status: ${matchStates[resource.data.state]}`:'Loading review status…'}</div>{!resource.data?<Panel title="Match review"><LoadFeedback error={resource.error} retry={resource.refresh}/></Panel>:<Review key={resource.etag} review={resource.data} etag={resource.etag!} tab={tab} canDecide={canDecide} reload={resource.refresh}/>}</>;
}
function Review({review,etag,tab,canDecide,reload}:{review:MatchReview;etag:string;tab:string;canDecide:boolean;reload:()=>void}){
  const [action,setAction]=useState<MatchOutcome|null>(null);const candidate=useClientResource<Client>(`/api/v1/clients/${review.candidateClientId}`);
  const agency=useClientResource<Relationship>(`/api/v1/relationships/${review.candidateRelationshipId}`);const active=tab==='Rule'?'Rule':'Match evidence';
  const reference=candidate.data?.reference ?? 'matched account';const open=review.state==='pending'||review.state==='queried';
  return <><Link href="/matches" className="client-back">← All match reviews</Link><RecordHeader type="Match review" title={`${review.submission.reference} · ${review.submission.identity.legalName}`} subtitle={`Intake submitted by ${review.submission.agencyName}`} status={matchStates[review.state]}
    facts={[{label:'Confidence',value:review.confidence},{label:'Matched account',value:candidate.data?.reference ?? (candidate.error?'Unavailable':'Loading…')},{label:'That account’s agency',value:agency.data?.agencyName ?? (agency.error?'Unavailable':'Loading…')},{label:'This submission',value:review.submission.agencyName},{label:'Rule in force',value:`Version ${review.rule.version}`},{label:'Quote capture',value:review.submission.quoteId?(review.submission.captureClosed?'Closed':'Draft attached'):'No quote attached'}]}
    tabs={['Match evidence','Rule'].map(label=>({label,href:`/matches/${review.id}?tab=${encodeURIComponent(label)}`}))} active={active} actions={!action&&<Link className="button" href={`/clients/${review.candidateClientId}`}>Open matched account</Link>}/>
    <div className="match-layout"><div className="match-main">
      <div hidden={active!=='Match evidence'}><div className="notice"><Status tone={open?'warning':review.state==='linked'?'success':'muted'}>{matchStates[review.state]}</Status><span>{open?'Compare the captured identity evidence and record a decision.':review.state==='linked'?'The intake is associated with the matched account.':review.state==='separate'?'The intake is recorded against its separate business account.':'The intake has been declined. The decision remains in the internal trail.'}</span></div>
      <Panel title="Signals compared" note="Evidence captured when this review was created"><DataTable caption="Signals compared" columns={['Signal','This submission',reference,'Weight','Result']}>{review.signals.map(signal=><tr key={signal.code}><td><strong>{signal.code.replaceAll('-',' ')}</strong><p className="client-help">{signal.summary}</p></td><td>{signal.submittedValue}</td><td>{signal.candidateValue}</td><td className="match-capitalize">{signal.weight}</td><td><Status tone={signal.result==='match'||signal.result==='near-match'?'warning':'muted'}>{signal.result.replaceAll('-',' ')}</Status></td></tr>)}</DataTable></Panel>
      <Panel title="Current account association"><div className="match-copy">{review.submission.linkedClientId?<><Link href={`/clients/${review.submission.linkedClientId}`}>Open associated account</Link><p>The association is retained when a review is reopened. The current review status determines whether it is decided.</p></>:<p>No account association has been selected for this intake.</p>}</div></Panel>
      <Panel title="Related business records">{!review.submission.quoteId && review.submission.linkedClientId && review.submission.linkedRelationshipId && canDecide && <p className="match-copy"><Link className="button" href={`/quotes/new?clientId=${review.submission.linkedClientId}&relationshipId=${review.submission.linkedRelationshipId}&matchSubmissionId=${review.submission.id}`}>Create quote from this intake</Link></p>}{review.submission.quoteId?<div className="match-copy"><Link href={`/quotes/${review.submission.quoteId}`}>Open attached quote</Link><p>{review.submission.captureClosed?'Quote capture is closed; matching decisions cannot change this record.':'Decisions use the saved quote version. An unresolved review prevents progression.'}</p><p>Policy and claims comparisons are not available yet.</p></div>:<EmptyState title="No quote attached">This review contains a saved intake identity. No portfolio or claims comparison is inferred.</EmptyState>}</Panel><DecisionTrail matchId={review.id}/><InformationRequests matchId={review.id}/></div>
      <div hidden={active!=='Rule'}><Panel title="Rule in force" note={`Captured configuration · version ${review.rule.version}`}><dl className="account-facts"><div><dt>Duplicate handling</dt><dd>{ruleLabels[review.rule.duplicateQuotePolicy]}</dd></div><div><dt>Review required</dt><dd>{review.rule.requireReview?'Yes':'No'}</dd></div><div><dt>Intake received</dt><dd>{clientDate(review.submission.createdAt,true)}</dd></div><div><dt>Recorded rule</dt><dd>{review.rule.summary}</dd></div></dl></Panel>
      <Panel title="What each rule means"><DataTable caption="Matching rule approaches" columns={['Rule','Approach']}><tr><td>{ruleLabels['allow-competing']}</td><td>Allow competing approaches to be considered independently.</td></tr><tr><td>{ruleLabels['broker-of-record']}</td><td>Assess the recorded broker protection period. A protection period is not available for this intake.</td></tr><tr><td>{ruleLabels.refer}</td><td>Hold the comparison for an underwriter to decide.</td></tr></DataTable></Panel><div className="notice"><Status tone="info">Internal review</Status><span>The comparison and decision evidence are restricted to authorised underwriting staff.</span></div></div>
    </div><aside className="match-rail" aria-label="Match decision"><Panel title="Decision" note={open?'Record a reason for your decision':'Decision retained in the trail'}>{action?<DecisionForm key={action} review={review} outcome={action} etag={etag} onCancel={()=>setAction(null)} onSaved={reload} onReload={reload}/>:<div className="match-actions">{canDecide&&!review.submission.captureClosed?availableDecisions(review.state).map(outcome=><button key={outcome} className={`button ${outcome==='link'?'button-primary':''} ${outcome==='decline'?'match-danger':''}`} onClick={()=>setAction(outcome)}>{outcome==='link'?`Link to ${reference}`:decisionLabels[outcome]}</button>):<p>{review.submission.captureClosed?'The attached quote is closed. Its decision history is retained.':'Your current access does not allow decisions.'}</p>}<button className="button" onClick={reload}>Refresh review</button></div>}</Panel>
    <Panel title="If linked"><dl className="account-facts"><div><dt>Shared</dt><dd>Business identity</dd></div><div><dt>Kept separate</dt><dd>Declared contacts and support instructions</dd></div><div><dt>Agency relationship</dt><dd>Only the submitting agency is associated</dd></div><div><dt>Existing records</dt><dd>Candidate contacts and support grants are preserved</dd></div></dl></Panel></aside></div></>;
}
function DecisionForm({review,outcome,etag,onCancel,onSaved,onReload}:{review:MatchReview;outcome:MatchOutcome;etag:string;onCancel:()=>void;onSaved:()=>void;onReload:()=>void}){
  const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [uncertain,setUncertain]=useState(false);const [stale,setStale]=useState(false);const [error,setError]=useState('');const lock=useRef(false);const receipt=useRef<{body:string;key:string;etag:string}|null>(null);
  async function save(event:FormEvent){event.preventDefault();if(lock.current)return;setError('');try{
    if(review.submission.quoteId&&!review.submission.quoteEtag)throw new Error('Reload the review to obtain the attached quote version.');
    if(!uncertain||!receipt.current)receipt.current={body:JSON.stringify({...matchPayload(outcome,reason),...(review.submission.quoteId?{expectedQuoteEtag:review.submission.quoteEtag}:{})}),key:crypto.randomUUID(),etag};
    lock.current=true;setBusy(true);const saved=receipt.current!;
    await clientFetch(`/api/v1/matches/${review.id}/decisions`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':await csrfToken(),'Idempotency-Key':saved.key,'If-Match':saved.etag},body:saved.body});receipt.current=null;setUncertain(false);onSaved();
  }catch(failure){setUncertain(uncertainFailure(failure));setStale(failure instanceof ClientError&&[409,412,428].includes(failure.status));setError(failure instanceof ClientError&&[409,412,428].includes(failure.status)?'The review or a related account has changed. Reload the saved review before deciding again.':failure instanceof Error?failure.message:'The decision could not be confirmed.');}finally{lock.current=false;setBusy(false);}}
  return <form className="client-form match-decision-form" onSubmit={event=>void save(event)}><h3>{decisionLabels[outcome]}</h3><p className="client-help">{outcome==='query'?'Record the information needed for follow-up. This records a request; it does not send a message.':outcome==='separate'?'Use the saved intake identity for a separate account. A previously created separate account will be reused.':outcome==='reopen'?'Keep the earlier decision and association in the trail, then make a new decision.':'Your reason will be retained in the restricted decision trail.'}</p>
    <label>Decision reason *<textarea required name="reason" rows={6} maxLength={1000} value={reason} disabled={busy||uncertain||stale} onChange={event=>setReason(event.target.value)}/></label>{error&&<div className="error-message" role="alert">{error}</div>}{uncertain&&<p role="status">The request is retained. Retry the same decision to confirm its result.</p>}
    <button className="button button-primary" type="submit" disabled={busy||stale}>{busy?'Saving…':uncertain?'Retry same decision':'Record decision'}</button><button className="button" type="button" disabled={busy||uncertain} onClick={onCancel}>Cancel decision</button>{stale&&<button className="button" type="button" onClick={onReload}>Reload saved review</button>}</form>;
}
function DecisionTrail({matchId}:{matchId:string}){
  const [history,setHistory]=useState(['']);const cursor=history.at(-1)!;const resource=useClientResource<Page<MatchDecision>>(`/api/v1/matches/${matchId}/decisions?pageSize=10${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);
  return <Panel title="Decision trail">{!resource.data?<LoadFeedback error={resource.error} retry={resource.refresh}/>:!resource.data.items.length?<EmptyState title="No decision recorded">The captured evidence is ready for review.</EmptyState>:<ol className="match-timeline">{resource.data.items.map(row=><li key={row.id}><strong>{decisionLabels[row.outcome]}</strong><div className="client-help">{row.actorLabel} · {clientDate(row.occurredAt,true)}</div><p>{row.reason}</p>{row.clientId&&<Link href={`/clients/${row.clientId}`}>Account recorded by this decision</Link>}</li>)}</ol>}<Paging total={resource.data?.totalCount} previous={history.length>1?()=>setHistory(x=>x.slice(0,-1)):undefined} next={resource.data?.nextCursor?()=>setHistory(x=>[...x,resource.data!.nextCursor!]):undefined}/></Panel>;
}
function InformationRequests({matchId}:{matchId:string}){
  const [history,setHistory]=useState(['']);const cursor=history.at(-1)!;const resource=useClientResource<Page<MatchRequest>>(`/api/v1/matches/${matchId}/information-requests?pageSize=10${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);
  return <Panel title="Information requests">{!resource.data?<LoadFeedback error={resource.error} retry={resource.refresh}/>:!resource.data.items.length?<EmptyState title="No information requests">Requests will appear here after a Query decision is recorded.</EmptyState>:<DataTable caption="Match information requests" columns={['Recorded','Request','Delivery status']}>{resource.data.items.map(row=><tr key={row.id}><td>{clientDate(row.recordedAt,true)}</td><td>{row.description}{row.correspondence&&<p><Link href={`/agents/${row.correspondence.agencyId}?tab=Messages`}>Open recorded internal correspondence</Link></p>}</td><td className="match-capitalize">{row.deliveryState}</td></tr>)}</DataTable>}<Paging total={resource.data?.totalCount} previous={history.length>1?()=>setHistory(x=>x.slice(0,-1)):undefined} next={resource.data?.nextCursor?()=>setHistory(x=>[...x,resource.data!.nextCursor!]):undefined}/></Panel>;
}
