import {addQuoteContracts} from './openapi-quotes.mjs';
import {addUnderwritingContracts} from './openapi-underwriting.mjs';
import {addServicingContracts} from './openapi-servicing.mjs';
import {addCommercialContracts} from './openapi-commercial-combined.mjs';
import {addPolicyTemporalContracts} from './openapi-policy-temporal.mjs';
import {addPolicyHistoryContracts} from './openapi-policy-history.mjs';
import {addOperationalRuntimeContracts} from './openapi-operational-runtime.mjs';
import {addFinanceLedgerContracts,writeFinanceLedgerTypes} from './openapi-finance-ledger.mjs';
import {addFinanceStatementContracts,writeFinanceStatementTypes} from './openapi-finance-statements.mjs';
import {addFinanceBordereauContracts,writeFinanceBordereauTypes} from './openapi-finance-bordereaux.mjs';
import {addFinanceSubmissionContracts,writeFinanceSubmissionTypes} from './openapi-finance-submissions.mjs';
import {addFinanceReceiptContracts,writeFinanceReceiptTypes} from './openapi-finance-receipts.mjs';
import {addFinanceReconciliationContracts,writeFinanceReconciliationTypes} from './openapi-finance-reconciliation.mjs';
import {addFinanceRefundContracts,writeFinanceRefundTypes} from './openapi-finance-refunds.mjs';
import {writeOperationalContracts} from './operations-contracts.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import {addOperationsApi} from './openapi-operations.mjs';
import {addAgencyFinanceApi} from './openapi-agency-finance.mjs';
import {addAdminReportsApi} from './openapi-admin-reports.mjs';
import {addReviewedApi} from './openapi-review-additions.mjs';
import {addFormContracts} from './openapi-form-contracts.mjs';
import {addPartyContracts} from './openapi-parties.mjs';
import {addAgencyContracts} from './openapi-agencies.mjs';
// Expand by bounded domain modules. Until control coverage is checked, this
// document is explicitly a work-in-progress, not the completed DES-04 contract.
export const schemas={};
export const ref=name=>({$ref:`#/components/schemas/${name}`});
export const text=(maxLength=200)=>({type:'string',minLength:1,maxLength});
export const enumeration=(...values)=>({type:'string',enum:values});
export const object=(properties,required=Object.keys(properties))=>({type:'object',additionalProperties:false,properties,required});
export const array=items=>({type:'array',items,maxItems:1000});
export const id={type:'string',format:'uuid'};
export const instant={type:'string',format:'date-time'};
export const date={type:'string',format:'date'};
export const boolean={type:'boolean'};
export const integer={type:'integer',minimum:0};
export const decimal={type:'string',pattern:'^-?(0|[1-9][0-9]{0,12})\\.[0-9]{2}$'};
const email={type:'string',format:'email',maxLength:254};
const token=text(2048);
const reason=object({reason:text(1000)});
schemas.Problem=object({type:{type:'string',format:'uri'},title:text(),status:{type:'integer',minimum:400,maximum:599},code:text(100),traceId:text(100),detail:text(2000),errors:array(object({path:text(500),code:text(100),message:text(1000)}))},['type','title','status','code','traceId']);
schemas.CommandResult=object({id,updatedAt:instant});
schemas.Job=object({id,kind:enumeration('rating','document','storage','email','lookup','mid','claims','payment','bordereau','export','diagnostic-probe'),state:enumeration('pending','leased','succeeded','failed'),attempts:integer,nextAttemptAt:instant,completedAt:instant,resultResourceId:id,errorCode:text(100)},['id','kind','state','attempts']);
schemas.ValidationIssue=object({path:text(500),code:text(100),message:text(1000),severity:enumeration('error','warning')});
schemas.Job.properties.attemptLimit={type:'integer',enum:[6,12,18]};
schemas.Job.properties.retryAllowed=boolean;
schemas.ValidationResult=object({valid:boolean,issues:array(ref('ValidationIssue'))});
schemas.PolicySnapshot={$ref:'./schemas/policy.schema.json'};
schemas.PolicyProposal={$ref:'./schemas/policy-draft.schema.json'};
schemas.Actor=object({id,displayName:text(),email,roles:array(text(60)),agencyId:{...id,type:['string','null']},scope:enumeration('internal','agency'),mfaEnabled:boolean});
schemas.Actor.allOf=[{if:{properties:{scope:{const:'internal'}}},then:{properties:{agencyId:{type:'null'}}},else:{properties:{agencyId:id}}}];
schemas.AuthResult={oneOf:[object({state:{const:'authenticated'},user:ref('Actor')}),object({state:{const:'mfa-required'},challengeId:id,expiresAt:instant})]};
schemas.SessionView=object({id,deviceLabel:text(),lastSeenAt:instant,expiresAt:instant,current:boolean});
schemas.Address=object({line1:text(),line2:text(),town:text(100),county:text(100),postcode:text(20),country:{const:'GB'}},['line1','town','postcode','country']);
schemas.ClientWrite=object({legalName:text(),entityType:enumeration('individual','partnership','limited-company','other'),companyNumber:text(30),address:ref('Address')},['legalName','entityType','address']);
schemas.Client=object({id,reference:text(40),...schemas.ClientWrite.properties},['id','reference',...schemas.ClientWrite.required]);
schemas.Relationship=object({id,clientId:id,agencyId:id,state:enumeration('active','inactive')});
schemas.ContactWrite=object({personId:id,firstName:text(100),surname:text(100),role:text(100),email,telephone:text(50),isPrimary:boolean,marketingConsent:object({email:boolean,telephone:boolean,recordedAt:instant,source:text()})},['firstName','surname','role','isPrimary','marketingConsent']);
schemas.Contact=object({id,...schemas.ContactWrite.properties},['id',...schemas.ContactWrite.required]);
schemas.FlagWrite=object({typeCode:text(60),internalCategory:text(100),internalInstruction:text(2000),agencyInstruction:text(1000),consentBasis:text(),reviewOn:date,reason:text(1000),visibleRelationshipIds:array(id)},['typeCode','internalCategory','internalInstruction','consentBasis','reviewOn','reason','visibleRelationshipIds']);
schemas.SupportFlag=object({id,personId:id,originRelationshipId:id,...schemas.FlagWrite.properties,endedAt:instant},['id','personId','originRelationshipId',...schemas.FlagWrite.required]);
schemas.MatchReview=object({id,quoteId:id,candidateClientId:id,confidence:enumeration('low','medium','high'),state:enumeration('pending','linked','separate','declined','queried'),signals:array(object({code:text(100),summary:text(500)})),ruleVersionId:id});
schemas.Quote=object({id,reference:text(40),relationshipId:id,productCode:enumeration('motor-trade-road-risks','motor-trade-combined','commercial-combined'),state:enumeration('draft','submitted','referred','terms-ready','accepted','bound','declined','withdrawn'),revision:integer,revisionId:id,proposal:ref('PolicyProposal'),validation:ref('ValidationResult')});
schemas.QuoteSummary=object({id,reference:text(40),clientName:text(),agencyName:text(),productCode:schemas.Quote.properties.productCode,state:schemas.Quote.properties.state,updatedAt:instant});
schemas.PolicySummary=object({id,reference:text(40),clientName:text(),agencyName:text(),productCode:schemas.Quote.properties.productCode,state:enumeration('scheduled','active','cancelled','expired'),currentTermId:id});
schemas.PolicyTerm=object({id,policyId:id,termNumber:{type:'integer',minimum:1},startsAt:instant,endsAt:instant,timeZone:{const:'Europe/London'}});
schemas.PolicyVersion=object({id,termId:id,transactionId:id,sequence:{type:'integer',minimum:1},effectiveAt:instant,processedAt:instant,kind:enumeration('new-business','MTA','renewal','cancellation'),snapshot:ref('PolicySnapshot')});
schemas.PolicyDraft=object({id,termId:id,kind:enumeration('MTA','renewal','cancellation'),revision:integer,baseVersionId:id,effectiveAt:instant,proposedTermEnd:instant,proposal:ref('PolicyProposal'),state:enumeration('draft','rated','referred','submitted','invited','accepted','issued','abandoned'),validation:ref('ValidationResult')},['id','termId','kind','revision','baseVersionId','effectiveAt','proposal','state','validation']);
schemas.Lease=object({draftId:id,holderUserId:id,leaseToken:token,expiresAt:instant});
schemas.RatingResult=object({id,inputHash:text(64),targetRevision:integer,ruleVersion:text(100),expiresAt:instant,premium:{$ref:'./schemas/policy.schema.json#/$defs/Premium'},factors:array(object({code:text(100),description:text(500),factor:{type:'string',pattern:'^[0-9]+(\\.[0-9]{1,6})?$'}})),referralIds:array(id)});
schemas.Referral=object({id,quoteRevisionId:id,draftId:id,ruleCode:text(100),authorityVersionId:id,reason:text(2000),state:enumeration('open','queried','approved','approved-with-conditions','declined','escalated'),conditions:array(object({id,description:text(1000),satisfied:boolean,evidenceDocumentId:id},['id','description','satisfied']))},['id','ruleCode','authorityVersionId','reason','state','conditions']);
schemas.AcceptanceWrite=object({ratingResultId:id,targetRevision:integer,termsHash:text(64),acceptedByLabel:text(),acceptedAt:instant,channel:enumeration('telephone','email','signed-document','in-person'),evidenceDocumentId:id},['ratingResultId','targetRevision','termsHash','acceptedByLabel','acceptedAt','channel']);
schemas.IssueWrite=object({ratingResultId:id,acceptanceId:id,targetRevision:integer,policyEtag:text(100),reason:text(1000)},['ratingResultId','acceptanceId','targetRevision','reason']);
schemas.IssueResult=object({policyId:id,termId:id,transactionId:id,versionId:id,invoiceId:id,jobIds:array(id)});
schemas.CancellationPreview=object({effectiveAt:instant,premium:decimal,tax:decimal,brokerCommission:decimal,fee:decimal,netCredit:decimal,cashRefundEligible:decimal,currency:{const:'GBP'},noticeRequired:boolean,referralIds:array(id)});

export const paths={};
const param=(name,location,schema,required=false)=>({name,in:location,required,schema});
const json=schema=>({'application/json':{schema}});
const errorResponse={description:'Safe problem response; codes and status semantics are defined in API-CONVENTIONS.md.',content:{'application/problem+json':{schema:ref('Problem')}}};
export function operation(method,path,name,permission,{input,output=ref('CommandResult'),status=200,existing=false,lease=false,publicAuth=false,idempotent=!publicAuth&&!path.startsWith('/account')&&path!=='/auth/logout',query=[],summary=name.replace(/([a-z])([A-Z])/g,'$1 $2')}={}){
 const write=method!=='get';
 const parameters=[...path.matchAll(/\{(\w+)\}/g)].map(m=>param(m[1],'path',id,true));
 parameters.push(...query.map(([key,schema])=>param(key,'query',schema)));
 if(write){if(idempotent)parameters.push(param('Idempotency-Key','header',{type:'string',minLength:16,maxLength:200},true));if(existing)parameters.push(param('If-Match','header',text(100),true));if(lease)parameters.push(param('X-Edit-Lease','header',token,true));}
 const responses={[status]:{description:status===202?'Durable work accepted; inspect Location for completion.':status===201?'Resource created.':'Operation succeeded.',headers:{ETag:{description:'Opaque resource version for subsequent conditional writes.',schema:text(100)},...(status===201||status===202?{Location:{description:'Created resource or durable job URI.',schema:{type:'string',format:'uri-reference'}}}:{})},content:json(output)}};
 for(const code of write?[400,401,403,404,409,412,422,428,429,503]:[400,401,403,404,429,503])responses[code]=errorResponse;
 const op={operationId:name,summary,description:`Requires ${permission}. Applies record and field scope; see API-CONVENTIONS.md for concurrency, replay and error semantics.`,tags:[path.split('/')[1]],'x-permission':permission,'x-idempotency':write&&idempotent?'required':'not-cached',security:publicAuth?(write?[{Csrf:[]}]:[]):write?[{Session:[],Csrf:[]}]:[{Session:[]}],parameters,responses};
 if(input)op.requestBody={required:true,content:json(input)};
 if(paths[path]?.[method])throw new Error(`Duplicate ${method} ${path}`);
 (paths[path]??={})[method]=op;
}
export function list(path,name,permission,item,query=[]){operation('get',path,name,permission,{output:object({items:array(item),nextCursor:text(2048),totalCount:integer},['items']),query:[['cursor',text(2048)],['pageSize',{type:'integer',minimum:1,maximum:100,default:25}],...query]});}
const op=operation;
op('get','/auth/csrf','getCsrf','public',{publicAuth:true,output:object({requestToken:token})});
op('post','/auth/login','login','public',{publicAuth:true,input:object({email,password:text(1024)}),output:ref('AuthResult')});
op('post','/auth/mfa/verify','verifyLoginMfa','challenge-owner',{publicAuth:true,input:object({challengeId:id,code:text(100),method:enumeration('totp','recovery-code')}),output:ref('AuthResult')});
op('post','/auth/logout','logout','authenticated');
op('post','/auth/password-reset/request','requestPasswordReset','public',{publicAuth:true,input:object({email}),output:object({accepted:boolean})});
op('post','/auth/password-reset/complete','completePasswordReset','reset-token-owner',{publicAuth:true,input:object({resetToken:token,newPassword:text(1024)}),output:object({completed:boolean})});
op('get','/account','getAccount','authenticated',{output:ref('Actor')});
op('put','/account','updateProfile','self',{existing:true,input:object({displayName:text()}),output:ref('Actor')});
op('post','/account/password','changePassword','self-recent-auth',{input:object({currentPassword:text(1024),newPassword:text(1024)})});
op('post','/account/mfa/enrolments','startMfaEnrolment','self-recent-auth',{input:object({password:text(1024),deviceName:text(100)},['password']),output:object({enrolmentId:id,otpauthUri:{type:'string',format:'uri'},expiresAt:instant}),status:201});
op('post','/account/mfa/enrolments/{enrolmentId}/confirm','confirmMfaEnrolment','enrolment-owner',{input:object({code:{type:'string',pattern:'^[0-9]{6}$'}}),output:object({state:{const:'verified-pending-activation'},recoveryCodes:array(text(100))})});
op('post','/account/mfa/enrolments/{enrolmentId}/activate','activateMfaEnrolment','enrolment-owner',{input:object({recoveryCodesSaved:{const:true}}),summary:'Enable MFA only after a verified unexpired enrolment and explicit recovery-code acknowledgement; atomically promote secret and code hashes'});
op('post','/account/mfa/enrolments/{enrolmentId}/cancel','cancelMfaEnrolment','enrolment-owner',{summary:'Cancel pending enrolment and destroy temporary secret/code hashes; do not disable already active MFA'});
op('post','/account/mfa/recovery-codes','replaceRecoveryCodes','self-recent-auth',{input:object({password:text(1024),code:text(100)}),output:object({recoveryCodes:array(text(100))})});
op('post','/account/mfa/disable','disableMfa','self-policy-permitting',{input:object({password:text(1024),code:text(100),reason:text(1000)})});
list('/account/sessions','listSessions','self',ref('SessionView'));
op('delete','/account/sessions/{sessionId}','revokeSession','self');
op('get','/jobs/{jobId}','getJob','subject-read',{output:ref('Job')});
op('post','/jobs/{jobId}/retry','retryJob','integration-retry',{existing:true,input:reason,output:ref('Job'),status:202});

list('/clients','listClients','client-read',ref('Client'),[['q',text()]]);
op('post','/clients','createClient','client-write',{input:ref('ClientWrite'),output:ref('Client'),status:201});
op('get','/clients/{clientId}','getClient','client-read',{output:ref('Client')});
op('put','/clients/{clientId}','updateClient','client-write',{existing:true,input:ref('ClientWrite'),output:ref('Client')});
list('/clients/{clientId}/relationships','listClientRelationships','client-read',ref('Relationship'));
op('post','/clients/{clientId}/relationships','createClientRelationship','client-write',{input:object({agencyId:id}),output:ref('Relationship'),status:201,existing:true});
list('/relationships/{relationshipId}/contacts','listContacts','relationship-read',ref('Contact'));
op('post','/relationships/{relationshipId}/contacts','createContact','contact-write',{input:ref('ContactWrite'),output:ref('Contact'),status:201,existing:true});
op('put','/relationships/{relationshipId}/contacts/{contactId}','updateContact','contact-write',{input:ref('ContactWrite'),output:ref('Contact'),existing:true});
op('post','/relationships/{relationshipId}/contacts/{contactId}/make-primary','makePrimaryContact','contact-write',{existing:true});
list('/relationships/{relationshipId}/people/{personId}/flags','listSupportFlags','support-internal-read',ref('SupportFlag'));
op('post','/relationships/{relationshipId}/people/{personId}/flags','createSupportFlag','support-write',{input:ref('FlagWrite'),output:ref('SupportFlag'),status:201,existing:true});
op('put','/flags/{flagId}','updateSupportFlag','support-write',{input:ref('FlagWrite'),output:ref('SupportFlag'),existing:true});
op('post','/flags/{flagId}/end','endSupportFlag','support-write',{input:reason,existing:true});
list('/matches','listMatchReviews','match-review',ref('MatchReview'),[['state',schemas.MatchReview.properties.state]]);
op('get','/matches/{matchId}','getMatchReview','match-review',{output:ref('MatchReview')});
op('post','/matches/{matchId}/decisions','decideMatch','match-review',{existing:true,input:object({outcome:enumeration('link','separate','decline','query','reopen'),reason:text(1000),candidateClientId:id},['outcome','reason']),output:ref('MatchReview')});

list('/quotes','listQuotes','quote-read',ref('QuoteSummary'),[['q',text()],['state',schemas.Quote.properties.state],['agencyId',id]]);
op('post','/quotes','createQuote','quote-write',{input:object({relationshipId:id,productVersionId:id}),output:ref('Quote'),status:201});
op('get','/quotes/{quoteId}','getQuote','quote-read',{output:ref('Quote')});
op('put','/quotes/{quoteId}/proposal','saveQuoteProposal','quote-write',{existing:true,input:ref('PolicyProposal'),output:ref('Quote')});
op('post','/quotes/{quoteId}/validate','validateQuote','quote-read',{existing:true,output:ref('ValidationResult')});
op('post','/quotes/{quoteId}/rate','rateQuote','quote-rate',{existing:true,output:ref('Job'),status:202});
op('post','/quotes/{quoteId}/submit','submitQuote','quote-submit',{existing:true,output:ref('Quote')});
op('post','/quotes/{quoteId}/withdraw','withdrawQuote','quote-write',{existing:true,input:reason,output:ref('Quote')});
op('post','/quotes/{quoteId}/terms','sendQuoteTerms','quote-terms',{existing:true,input:object({ratingResultId:id,recipientContactIds:array(id),templateVersionId:id}),output:ref('Job'),status:202});
op('post','/quotes/{quoteId}/acceptances','recordQuoteAcceptance','quote-acceptance',{existing:true,input:ref('AcceptanceWrite'),status:201});
op('post','/quotes/{quoteId}/issue','issueQuote','policy-issue-within-authority',{existing:true,input:ref('IssueWrite'),output:ref('IssueResult'),status:201});
op('get','/ratings/{ratingId}','getRating','target-read',{output:ref('RatingResult')});
list('/referrals','listReferrals','underwriting-read',ref('Referral'),[['quoteId',id],['draftId',id],['state',schemas.Referral.properties.state]]);
op('get','/referrals/{referralId}','getReferral','underwriting-read',{output:ref('Referral')});
op('post','/referrals/{referralId}/decisions','decideReferral','underwriting-decide-within-authority',{existing:true,input:object({outcome:enumeration('approve','approve-with-conditions','query','decline','reopen'),reason:text(2000),targetHash:text(64),conditions:array(object({description:text(1000),evidenceRequired:boolean})),evidenceDocumentId:id},['outcome','reason','targetHash','conditions']),output:ref('Referral')});

list('/policies','listPolicies','policy-read',ref('PolicySummary'),[['q',text()],['agencyId',id],['state',schemas.PolicySummary.properties.state]]);
op('get','/policies/{policyId}','getPolicy','policy-read',{output:ref('PolicySummary')});
list('/policies/{policyId}/terms','listPolicyTerms','policy-read',ref('PolicyTerm'));
list('/terms/{termId}/versions','listPolicyVersions','policy-read',ref('PolicyVersion'));
op('get','/terms/{termId}/as-at','getPolicyAsAt','policy-read',{query:[['effectiveAt',instant],['knownAt',instant]],output:ref('PolicyVersion')});
op('get','/versions/{versionId}','getPolicyVersion','policy-read',{output:ref('PolicyVersion')});
list('/terms/{termId}/drafts','listPolicyDrafts','policy-read',ref('PolicyDraft'));
op('post','/terms/{termId}/drafts','createPolicyDraft','policy-draft-write',{existing:true,input:object({kind:schemas.PolicyDraft.properties.kind,baseVersionId:id,effectiveAt:instant,proposedTermEnd:instant,reason:text(1000)},['kind','baseVersionId','effectiveAt','reason']),output:ref('PolicyDraft'),status:201});
op('get','/drafts/{draftId}','getPolicyDraft','policy-read',{output:ref('PolicyDraft')});
op('post','/drafts/{draftId}/lease','acquireDraftLease','policy-draft-write',{input:object({takeover:boolean,reason:text(1000)},['takeover']),output:ref('Lease')});
op('put','/drafts/{draftId}/lease','renewDraftLease','lease-owner',{lease:true,output:ref('Lease')});
op('delete','/drafts/{draftId}/lease','releaseDraftLease','lease-owner',{lease:true});
op('put','/drafts/{draftId}/proposal','savePolicyDraft','policy-draft-write',{existing:true,lease:true,input:object({proposal:ref('PolicyProposal'),effectiveAt:instant,proposedTermEnd:instant,reason:text(1000)},['proposal','effectiveAt','reason']),output:ref('PolicyDraft')});
op('post','/drafts/{draftId}/rate','ratePolicyDraft','policy-draft-rate',{existing:true,lease:true,output:ref('Job'),status:202});
op('post','/drafts/{draftId}/submit','submitPolicyDraft','policy-draft-submit',{existing:true,lease:true,output:ref('PolicyDraft')});
op('post','/drafts/{draftId}/abandon','abandonPolicyDraft','policy-draft-write',{existing:true,lease:true,input:reason,output:ref('PolicyDraft')});
op('post','/drafts/{draftId}/acceptances','recordDraftAcceptance','policy-acceptance',{existing:true,lease:true,input:ref('AcceptanceWrite'),status:201});
op('post','/drafts/{draftId}/issue','issuePolicyDraft','policy-issue-within-authority',{existing:true,lease:true,input:ref('IssueWrite'),output:ref('IssueResult'),status:201});
// Renewal invitations use the implemented exact-terms preparation and delivery
// operations shared with servicing; there is no second invitation command.
op('post','/terms/{termId}/lapse','lapseRenewal','renewal-lapse',{existing:true,input:reason});
op('get','/drafts/{draftId}/cancellation-preview','getCancellationPreview','cancellation-review',{output:ref('CancellationPreview')});

addOperationsApi({schemas,ref,text,enumeration,object,array,id,instant,date,boolean,integer,decimal,operation,list,paths});
addAgencyFinanceApi({schemas,ref,text,enumeration,object,array,id,instant,date,boolean,integer,decimal,operation,list,paths});
addAdminReportsApi({schemas,ref,text,enumeration,object,array,id,instant,date,boolean,integer,decimal,operation,list,paths});
addReviewedApi({schemas,ref,text,enumeration,object,array,id,instant,date,boolean,integer,decimal,operation,list,paths});
addFormContracts({schemas,ref,text,enumeration,object,array,id,instant,date,boolean,integer,decimal,operation,list,paths});
addPartyContracts({schemas,ref,text,enumeration,object,array,id,instant,date,boolean,integer,decimal,operation,list,paths});
addAgencyContracts({schemas,ref,text,enumeration,object,array,id,instant,date,boolean,integer,decimal,operation,list,paths});
addQuoteContracts({schemas,ref,text,enumeration,object,array,id,instant,date,boolean,integer,decimal,operation,list,paths});
addUnderwritingContracts({schemas,ref,operation,paths});
addServicingContracts({schemas,ref,operation,paths});
addCommercialContracts({schemas,ref,operation,paths});
addPolicyTemporalContracts({schemas,ref,operation,paths});
addPolicyHistoryContracts({schemas,ref,operation,paths});
addOperationalRuntimeContracts({schemas,ref,operation,list,paths,object,id,text});
addFinanceLedgerContracts({schemas,ref,operation,paths,id,instant,date,decimal});
addFinanceStatementContracts({schemas,ref,operation,paths,id,instant,date,decimal});
addFinanceBordereauContracts({schemas,ref,operation,paths,id,instant,date,decimal});
addFinanceSubmissionContracts({schemas,ref,operation,paths,id,instant});
addFinanceReceiptContracts({schemas,ref,operation,paths,id,instant,date,decimal});
addFinanceReconciliationContracts({schemas,ref,operation,paths,id,instant,date,decimal});
addFinanceRefundContracts({schemas,ref,operation,paths,id,instant,decimal});
await writeOperationalContracts();
await writeFinanceLedgerTypes();
await writeFinanceStatementTypes();
await writeFinanceBordereauTypes();
await writeFinanceSubmissionTypes();
await writeFinanceReceiptTypes();
await writeFinanceReconciliationTypes();
await writeFinanceRefundTypes();
const tags=[...new Set(Object.keys(paths).map(p=>p.split('/')[1]))].sort().map(name=>({name,description:`Scoped ${name} operations.`}));
const document={openapi:'3.1.1',info:{title:'Cover MGA Back Office API',version:'1.0.0',description:'Version 1 implementation contract. Reviewed prototype-control mappings, conditional capture rules and internal adapter schemas accompany this API. Runtime authorization, persistence and product validation are verified during implementation phases.'},servers:[{url:'/api/v1',description:'Same-origin application API'}],tags,security:[{Session:[]}],paths,components:{securitySchemes:{Session:{type:'apiKey',in:'cookie',name:'__Host-cover-session',description:'Opaque server-side session; development cookie has a separate name.'},Csrf:{type:'apiKey',in:'header',name:'X-CSRF-Token',description:'ASP.NET antiforgery request token paired with the antiforgery cookie.'}},schemas}};
await mkdir('contracts',{recursive:true});
await writeFile('contracts/openapi.json',JSON.stringify(document,null,2)+'\n');
console.log(`Generated ${Object.values(paths).reduce((n,p)=>n+Object.keys(p).length,0)} operations.`);
