'use client';
import {useState} from 'react';
import {Panel,DataTable} from '../primitives';
import {useAdminResource} from './use-admin-resource';
import {adminIntent} from '../../lib/admin-api';
type Health={families:{kind:string;queued:number;succeeded:number;failed:number;lastSuccess:string|null;lastFailure:string|null}[];settings:{id:string;scope:string;version:number;scenario:string|null;options:string[];etag:string}[];scenarioEditing:boolean};
type Job={id:string;kind:string;state:string;attempts:number;attemptLimit:number;createdAt:string;nextAttemptAt:string;completedAt:string|null;errorCode:string|null;subjectRecordId:string|null;scenarioVersionId:string|null;retryAllowed:boolean;etag:string};
type Jobs={items:Job[];asOf:string;nextOffset:number|null;totalCount:number};
type Detail={job:Job;attempts:{id:string;attemptNumber:number;startedAt:string;endedAt:string|null;outcome:string;errorCode:string|null}[];providerOperations:{id:string;createdAt:string}[]};
const date=(value:string|null)=>value?new Date(value).toLocaleString():'—';
export function IntegrationOversight(){
 const health=useAdminResource<Health>('/admin/integration-health'),[kind,setKind]=useState(''),[state,setState]=useState(''),[page,setPage]=useState({offset:0,asOf:''}),[selected,setSelected]=useState('');
 const params=new URLSearchParams({offset:String(page.offset),...(kind?{kind}:{}),...(state?{state}:{}),...(page.asOf?{asOf:page.asOf}:{})});
 const jobs=useAdminResource<Jobs>('/admin/oversight/jobs?'+params.toString());
 return <div className="operations-stack"><div aria-live="polite">{health.notice&&<p className="notice">{health.notice}</p>}{(health.error||jobs.error)&&<p role="alert">{health.error||jobs.error}</p>}{health.retry&&<button className="button" disabled={health.busy} onClick={()=>void health.send(health.retry!)}>Retry same scenario change</button>}</div>
 <Panel title="Adapter health" note="Saved outcomes across implemented workers. Zero counts mean no recorded jobs; they do not prove a provider is available."><button className="button" onClick={()=>{health.reload();jobs.reload();}}>Refresh saved health</button>{health.data&&<DataTable caption="Adapter health" columns={['Family','Queued / running','Succeeded','Failed','Latest success','Latest failure']}>{health.data.families.map(x=><tr key={x.kind}><td>{x.kind}</td><td>{x.queued}</td><td>{x.succeeded}</td><td>{x.failed}</td><td>{date(x.lastSuccess)}</td><td>{date(x.lastFailure)}</td></tr>)}</DataTable>}</Panel>
 <Panel title="Future demo scenarios" note="Changing a scenario affects newly queued work. Existing jobs keep their saved scenario version and provider operation.">{health.data?.settings.map(x=><details key={x.id}><summary>{x.scope} · version {x.version} · {x.scenario??'Invalid configuration'}</summary><form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void health.send(adminIntent('/admin/integration-scenarios','POST',{scope:x.scope,scenario:f.get('scenario'),reason:f.get('reason')},x.etag));}}><fieldset disabled={health.locked||!health.data!.scenarioEditing||x.scenario===null}><legend>Publish scenario successor</legend><label>Scenario<select name="scenario" defaultValue={x.scenario??undefined}>{x.options.map(o=><option key={o}>{o}</option>)}</select></label><label>Scenario change reason<textarea name="reason" required maxLength={1000}/></label><button className="button">Publish demo scenario</button></fieldset></form></details>)}{health.data&&!health.data.scenarioEditing&&<p>Scenario changes are available only in the local demonstration environment.</p>}</Panel>
 <Panel title="All operational jobs" note="This view contains safe job metadata and attempt outcomes. Business recovery remains in its owning workflow; eligible diagnostic recovery is available below."><div className="operations-toolbar"><label>Worker family<select value={kind} onChange={e=>{setKind(e.target.value);setPage({offset:0,asOf:''});}}><option value="">All families</option>{health.data?.families.map(x=><option key={x.kind}>{x.kind}</option>)}</select></label><label>Job state<select value={state} onChange={e=>{setState(e.target.value);setPage({offset:0,asOf:''});}}><option value="">All states</option>{['pending','leased','succeeded','failed'].map(x=><option key={x}>{x}</option>)}</select></label></div>{jobs.data&&<><DataTable caption="All operational jobs" columns={['Job','Family','State','Attempts','Outcome','Detail']}>{jobs.data.items.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.kind}</td><td>{x.state}</td><td>{x.attempts} / {x.attemptLimit}</td><td>{x.errorCode??'—'}</td><td><button className="button" onClick={()=>setSelected(x.id)}>Inspect job</button></td></tr>)}</DataTable><div className="panel-footer operations-actions"><span>{jobs.data.totalCount} matching jobs</span><button className="button" disabled={page.offset===0} onClick={()=>setPage({offset:0,asOf:''})}>First jobs</button><button className="button" disabled={jobs.data.nextOffset===null} onClick={()=>setPage({offset:jobs.data!.nextOffset!,asOf:jobs.data!.asOf})}>Next jobs</button></div></>}</Panel>
 {selected&&<JobDetail key={selected} id={selected}/>}
 </div>;
}
function JobDetail({id}:{id:string}){const r=useAdminResource<Detail>(`/admin/oversight/jobs/${id}`);return <Panel title="Saved job and provider attempts">{r.error&&<p role="alert">{r.error}</p>}{r.data&&<><dl><dt>Job</dt><dd>{r.data.job.id}</dd><dt>Source record</dt><dd>{r.data.job.subjectRecordId??'None'}</dd><dt>Pinned scenario version</dt><dd>{r.data.job.scenarioVersionId??'Not used'}</dd><dt>Saved provider operations</dt><dd>{r.data.providerOperations.map(x=>x.id).join(', ')||'None recorded'}</dd></dl><DataTable caption="Provider attempts" columns={['Attempt','Started','Ended','Outcome','Error']}>{r.data.attempts.map(x=><tr key={x.id}><td>{x.attemptNumber}</td><td>{date(x.startedAt)}</td><td>{date(x.endedAt)}</td><td>{x.outcome}</td><td>{x.errorCode??'—'}</td></tr>)}</DataTable>{r.data.attempts.length===0&&<p>No adapter attempts recorded. Some local workers record their outcome directly on the job.</p>}</>}</Panel>;}

type Audit={id:string;actorId:string|null;actorLabel:string;eventType:string;occurredAt:string;subjectRecordId:string|null;correlationId:string;reason:string|null;summary:string};
type AuditPage={items:Audit[];nextCursor?:string;totalCount:number};
export function AdministrationAudit(){
 const [filter,setFilter]=useState(''),[cursor,setCursor]=useState(''),[selected,setSelected]=useState('');
 const r=useAdminResource<AuditPage>(`/admin/audit?pageSize=20${filter?'&'+filter:''}${cursor?'&cursor='+encodeURIComponent(cursor):''}`);
 return <div className="operations-stack"><Panel title="Audit log" note="Current administrators can inspect recorded actions. Credential, session, invitation and MFA payloads are excluded from details."><form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),p=new URLSearchParams();for(const key of ['eventType','actorId','subjectRecordId','reason'])if(f.get(key))p.set(key,String(f.get(key)).trim());for(const key of ['from','to'])if(f.get(key))p.set(key,new Date(String(f.get(key))).toISOString());setFilter(p.toString());setCursor('');r.reload();}}><label>Action code<input name="eventType" maxLength={100}/></label><label>Actor ID<input name="actorId" placeholder="Optional user UUID"/></label><label>Entity ID<input name="subjectRecordId" placeholder="Optional record UUID"/></label><label>From (local time)<input type="datetime-local" name="from"/></label><label>To (local time)<input type="datetime-local" name="to"/></label><label>Reason contains<input name="reason" maxLength={1000}/></label><div className="operations-actions"><button className="button">Apply audit filters</button><button className="button" type="reset" onClick={()=>{setFilter('');setCursor('');r.reload();}}>Clear audit filters</button></div></form>{r.error&&<p role="alert">{r.error}</p>}{r.data&&<><DataTable caption="Audit log" columns={['Time','Actor','Action','Reason','Detail']}>{r.data.items.map(x=><tr key={x.id}><td>{date(x.occurredAt)}</td><td>{x.actorLabel}</td><td>{x.eventType}</td><td>{x.reason??'—'}</td><td><button className="button" onClick={()=>setSelected(x.id)}>View audit detail</button></td></tr>)}</DataTable><div className="panel-footer operations-actions"><span>{r.data.totalCount} matching entries</span><button className="button" disabled={!cursor} onClick={()=>setCursor('')}>First page</button><button className="button" disabled={!r.data.nextCursor} onClick={()=>setCursor(r.data!.nextCursor!)}>Next page</button></div></>}</Panel>{selected&&<AuditDetail key={selected} id={selected}/>}</div>;
}
function AuditDetail({id}:{id:string}){const r=useAdminResource<Audit&{before:unknown;after:unknown}>(`/admin/audit/${id}`);return <Panel title="Audit detail">{r.error&&<p role="alert">{r.error}</p>}{r.data&&<><dl><dt>Action</dt><dd>{r.data.eventType}</dd><dt>Entity</dt><dd>{r.data.subjectRecordId??'Not recorded'}</dd><dt>Actor</dt><dd>{r.data.actorId??'System'}</dd><dt>Reason</dt><dd>{r.data.reason??'Not recorded'}</dd><dt>Correlation</dt><dd>{r.data.correlationId}</dd></dl><h3>Before</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(r.data.before,null,2)}</pre><h3>After</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(r.data.after,null,2)}</pre><p>Only approved fields are disclosed. Omitted fields are not evidence of an unchanged value.</p></>}</Panel>;}
