'use client';
import {useState} from 'react';
import {Panel,DataTable} from '../primitives';
import {adminIntent,adminSend} from '../../lib/admin-api';
import {useAdminResource} from './use-admin-resource';
type User={id:string;email:string;displayName:string;state:string;teamId:string;roles:string[];etag:string;mfaEnabled:boolean;mustReset:boolean};
type Change={userId:string;etag:string;email:string;teamId:string;roles:string[];resetMfa:boolean;reason:string};
type Data={users:User[];teams:{id:string;name:string;etag:string}[];roles:string[];requests:{id:string;requestedBy:string;state:string;proposal:Change;etag:string;decisionReason:string|null}[];deliveries:{id:string;userId:string;kind:string;expiresAt:string}[];demoDelivery:boolean};
export function UserAdministration(){
 const r=useAdminResource<Data>('/admin/users'),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[delivery,setDelivery]=useState(''),[error,setError]=useState('');
 const user=r.data?.users.find(x=>x.id===selected);
 async function reveal(id:string){try{const value=await adminSend<{token:string}>(adminIntent(`/admin/identity-deliveries/${id}/demo-reveal`,'POST',{}));setDelivery(value.token);setError('');}catch(e){setError((e as Error).message);}}
 return <div className="operations-stack"><div aria-live="polite">{r.notice&&<p className="notice">{r.notice}</p>}{(r.error||error)&&<p role="alert">{r.error||error}</p>}{r.retry&&<button className="button" disabled={r.busy} onClick={()=>void r.send(r.retry!)}>Retry same action</button>}</div>
 <Panel title="Internal users" note="New invitations start with the servicing role. Email, team, roles and MFA reset require another administrator's approval."><label>Search users<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="button" disabled={r.locked} onClick={r.reload}>Reload users</button>{r.data?<DataTable caption="Internal users" columns={['User','Roles','Status','Action']}>{r.data.users.filter(x=>(x.displayName+' '+x.email).toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x.id}><td>{x.displayName}<br/>{x.email}</td><td>{x.roles.join(', ')}</td><td>{x.state}{x.mustReset?' · password reset required':''}{x.mfaEnabled?' · MFA enabled':''}</td><td><button className="button" onClick={()=>{setSelected(x.id);setDelivery('');}}>Manage {x.displayName}</button></td></tr>)}</DataTable>:<p role="status">Loading users…</p>}</Panel>
 {user&&r.data&&<Panel title={user.displayName}><UserForm key={user.id+user.etag} user={user} r={r}/><form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void r.send(adminIntent(`/admin/users/${user.id}/${f.get('action')}`,'POST',{reason:f.get('reason')},user.etag));}}><fieldset disabled={r.locked}><legend>Immediate access action</legend><label>Action<select name="action"><option value="revoke-sessions">Revoke every session</option>{user.state==='suspended'?<option value="resume">Resume account</option>:<option value="suspend">Suspend account</option>}<option value="force-reset">Require password reset</option></select></label><label>Action reason<textarea required name="reason" maxLength={1000}/></label><button className="button">Apply access action</button></fieldset></form>
 {r.data.demoDelivery&&r.data.deliveries.filter(x=>x.userId===user.id).map(x=><p key={x.id}>{x.kind} · expires {new Date(x.expiresAt).toLocaleString()} <button className="button" onClick={()=>void reveal(x.id)}>View local demo delivery</button></p>)}{delivery&&<div className="notice"><p>Local demonstration delivery. Treat this one-use token as a password.</p><input aria-label="One-use delivery token" readOnly value={delivery}/><button className="button" onClick={()=>setDelivery('')}>Hide token</button><p>Use the invitation or password reset form on the sign-in page.</p></div>}</Panel>}
 <Panel title="Invite a colleague"><form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void r.send(adminIntent('/admin/users/invitations','POST',{email:f.get('email'),displayName:f.get('name'),teamId:f.get('team'),reason:f.get('reason')}));}}><fieldset disabled={r.locked||!r.data}><legend>Internal invitation</legend><label>Display name<input name="name" required maxLength={200}/></label><label>Email address<input type="email" name="email" required maxLength={254}/></label><label>Team<select required name="team">{r.data?.teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Invitation reason<textarea name="reason" required maxLength={1000}/></label><button className="button">Create invitation</button></fieldset></form></Panel>
 <Panel title="User change approvals">{r.data?.requests.map(x=><details key={x.id}><summary>{x.state} · {r.data!.users.find(u=>u.id===x.proposal.userId)?.displayName} · {x.proposal.reason}</summary><p>Requested by {r.data!.users.find(u=>u.id===x.requestedBy)?.displayName}. Proposed email: {x.proposal.email}. Team: {r.data!.teams.find(t=>t.id===x.proposal.teamId)?.name}. Roles: {x.proposal.roles.join(', ')}. Reset MFA: {x.proposal.resetMfa?'Yes':'No'}.</p>{x.decisionReason&&<p>{x.decisionReason}</p>}{x.state==='pending'&&<form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void r.send(adminIntent(`/admin/users/requests/${x.id}/decision`,'POST',{approve:f.get('decision')==='approve',reason:f.get('reason')},x.etag));}}><label>Decision<select name="decision"><option value="reject">Reject</option><option value="approve">Approve</option></select></label><label>Decision reason<textarea name="reason" required maxLength={1000}/></label><button className="button" disabled={r.locked}>Record user decision</button></form>}</details>)}</Panel>
 <Panel title="Teams">{r.data?.teams.map(x=><form className="task-form" key={x.id+x.etag} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void r.send(adminIntent(`/admin/teams/${x.id}`,'PUT',{name:f.get('name'),reason:f.get('reason')},x.etag));}}><label>Team name<input name="name" required maxLength={100} defaultValue={x.name}/></label><label>Team change reason<input name="reason" required maxLength={1000}/></label><button className="button" disabled={r.locked}>Rename team</button></form>)}<form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void r.send(adminIntent('/admin/teams','POST',{name:f.get('name'),reason:f.get('reason')}));}}><label>New team name<input name="name" required maxLength={100}/></label><label>New team reason<input name="reason" required maxLength={1000}/></label><button className="button" disabled={r.locked}>Create team</button></form></Panel>
 </div>;
}
function UserForm({user,r}:{user:User;r:ReturnType<typeof useAdminResource<Data>>}){
 return <form className="task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void r.send(adminIntent('/admin/users/requests','POST',{userId:user.id,etag:user.etag,email:f.get('email'),teamId:f.get('team'),roles:f.getAll('roles'),resetMfa:f.has('resetMfa'),reason:f.get('reason')}));}}><fieldset disabled={r.locked}><legend>Request protected change</legend><label>Proposed email<input required name="email" type="email" defaultValue={user.email} maxLength={254}/></label><label>Proposed team<select name="team" defaultValue={user.teamId}>{r.data!.teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><fieldset><legend>Proposed roles</legend>{r.data!.roles.map(x=><label className="task-checkbox" key={x}><input type="checkbox" name="roles" value={x} defaultChecked={user.roles.includes(x)}/>{x}</label>)}</fieldset><label className="task-checkbox"><input type="checkbox" name="resetMfa"/>Reset MFA enrolment</label><label>Request reason<textarea name="reason" required maxLength={1000}/></label><button className="button button-primary">Request user change</button></fieldset></form>;
}
