using BackOffice.Infrastructure.Identity;
using Microsoft.AspNetCore.Authentication;
namespace BackOffice.Api;
public static class AccountSecurityEndpoints
{
    public sealed record PasswordInput(string Password,string NewPassword,string? Code);
    public sealed record EmailInput(string Email);
    public sealed record ResetInput(string Token,string NewPassword,string? Code);
    public sealed record CodeInput(string Code);
    public sealed record ChallengeInput(string ChallengeToken,string Code);
    public sealed record ReasonInput(string Reason);
    public sealed record IdentityInput(string Email,Guid TeamId,string[] Roles,string Reason);
    public static void MapAccountSecurity(this WebApplication app)
    {
        app.MapGet("/api/v1/account/security",(HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>Results.Json(await s.ReadAsync(AccountSecurityService.Identity(c.User),c.RequestAborted)))).RequireAuthorization();
        app.MapPut("/api/v1/account/profile",(AccountProfile input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{await s.ProfileAsync(AccountSecurityService.Identity(c.User),input,c.RequestAborted);return Results.Ok(new{state="saved"});})).RequireAuthorization();
        app.MapPost("/api/v1/account/identity-requests",(IdentityInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{await s.RequestIdentityAsync(AccountSecurityService.Identity(c.User),input.Email,input.TeamId,input.Roles,input.Reason,c.RequestAborted);return Results.Ok(new{state="requested"});})).RequireAuthorization();
        app.MapPost("/api/v1/account/password",(PasswordInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{await s.PasswordAsync(AccountSecurityService.Identity(c.User),new(input.Password,input.Code),input.NewPassword,c.RequestAborted);await c.SignOutAsync();return Results.Ok(new{state="sign-in-required"});})).RequireAuthorization().RequireRateLimiting("login");
        app.MapPost("/api/v1/auth/password-forgot",(EmailInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{await s.ForgotAsync(input.Email,c.RequestAborted);return Results.Ok(new{state="requested",message="If an eligible account exists, reset instructions are available through the configured local delivery."});})).AllowAnonymous().RequireRateLimiting("login");
        app.MapPost("/api/v1/auth/password-reset",(ResetInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>await s.ResetAsync(input.Token,input.NewPassword,input.Code,c.RequestAborted)?Results.Ok(new{state="reset"}):IdentityEndpoints.Problem(c,400,"reset-invalid","Reset token or verification is unavailable."))).AllowAnonymous().RequireRateLimiting("login");
        app.MapPost("/api/v1/account/mfa/enrolments",(AccountProof input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>Results.Json(await s.EnrolAsync(AccountSecurityService.Identity(c.User),input.Password,c.RequestAborted)))).RequireAuthorization().RequireRateLimiting("login");
        app.MapPost("/api/v1/account/mfa/enrolments/{id:guid}/confirm",(Guid id,CodeInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{var codes=await s.ConfirmAsync(AccountSecurityService.Identity(c.User),id,input.Code,c.RequestAborted);if(codes==null)return IdentityEndpoints.Problem(c,400,"mfa-verification-failed","The code or enrolment is unavailable.");await c.SignOutAsync();return Results.Ok(new{state="enabled",recoveryCodes=codes});})).RequireAuthorization().RequireRateLimiting("login");
        app.MapPost("/api/v1/account/mfa/enrolments/{id:guid}/cancel",(Guid id,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{await s.CancelAsync(AccountSecurityService.Identity(c.User),id,c.RequestAborted);return Results.Ok(new{state="cancelled"});})).RequireAuthorization();
        app.MapPost("/api/v1/account/mfa/recovery-codes",(AccountProof input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>Results.Ok(new{recoveryCodes=await s.ReplaceCodesAsync(AccountSecurityService.Identity(c.User),input,c.RequestAborted)}))).RequireAuthorization().RequireRateLimiting("login");
        app.MapPost("/api/v1/account/mfa/disable",(AccountProof input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{await s.DisableAsync(AccountSecurityService.Identity(c.User),input,c.RequestAborted);await c.SignOutAsync();return Results.Ok(new{state="disabled"});})).RequireAuthorization().RequireRateLimiting("login");
        app.MapPost("/api/v1/auth/mfa",(ChallengeInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{var identity=await s.CompleteLoginAsync(input.ChallengeToken,input.Code,c.RequestAborted);if(identity==null)return IdentityEndpoints.Problem(c,401,"invalid-factor","The code or challenge is unavailable.");if(c.User.Identity?.IsAuthenticated==true)await c.SignOutAsync();await c.SignInAsync(identity.Principal,new AuthenticationProperties{IsPersistent=false});return Results.Ok(new{state="authenticated",user=identity.View});})).AllowAnonymous().RequireRateLimiting("login");
        app.MapPost("/api/v1/account/sessions/{id:guid}/revoke",(Guid id,ReasonInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{var actor=AccountSecurityService.Identity(c.User);await s.SessionsAsync(actor,id,false,input.Reason,c.RequestAborted);if(actor.SessionId==id)await c.SignOutAsync();return Results.Ok(new{state="revoked"});})).RequireAuthorization();
        app.MapPost("/api/v1/account/sessions/revoke-others",(ReasonInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{await s.SessionsAsync(AccountSecurityService.Identity(c.User),null,true,input.Reason,c.RequestAborted);return Results.Ok(new{state="revoked"});})).RequireAuthorization();
        app.MapPost("/api/v1/account/security-reports",(ReasonInput input,HttpContext c,AccountSecurityService s)=>AdministrationEndpoints.Work(c,async()=>{await s.ReportAsync(AccountSecurityService.Identity(c.User),input.Reason,c.RequestAborted);return Results.Ok(new{state="reported"});})).RequireAuthorization();
    }
}
