'use client';
import {commercialPropertySummary,type CommercialPolicyView} from '../../lib/commercial-policy';
import type {QuoteObject,QuoteValue} from '../../lib/quotes';
import {formatCommercialMoney as money} from '../../lib/commercial-policy';
import {DataTable,Panel} from '../primitives';
import {QuoteProposalDetails} from '../quotes/quote-history';
import {CommercialExposurePanel} from './commercial-exposure-panel';

export const commercialPolicyTabs=['Overview','Risk details','Cover','Property schedule','Liability & employees','Business interruption','Transactions','Documents','Notes','Messages','History'] as const;
export type CommercialPolicyTab=typeof commercialPolicyTabs[number];
const text=(value:QuoteValue|undefined):string=>typeof value==='string'?value:typeof value==='number'?String(value):typeof value==='boolean'?(value?'Yes':'No'):value&&typeof value==='object'&&!Array.isArray(value)&&typeof value.label==='string'?value.label:'Not recorded';
const object=(value:QuoteValue|undefined):QuoteObject=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const amount=(value:QuoteValue|undefined)=>typeof value==='string'?money(value):'Not recorded';
const sectionName=(value:QuoteValue|undefined)=>text(value).replaceAll('-',' ').replace(/^./,x=>x.toUpperCase());
export function CommercialPolicySections({policy,tab,questionLabels}:{policy:CommercialPolicyView;tab:CommercialPolicyTab;questionLabels:Record<string,string>}) {
 const snapshot=policy.snapshot,risk=snapshot.risk,locations=risk.locations??[],wages=risk.wages??[],summary=commercialPropertySummary(locations);
 const sections=Array.isArray(snapshot.cover.sections)?snapshot.cover.sections.map(object):[];
 const details=(value:unknown)=><QuoteProposalDetails proposal={snapshot} value={value} questionLabels={questionLabels}/>;
 const fields=(values:[string,string][])=><dl className="underwriting-provenance">{values.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;
 const date=(value:string)=>new Date(value).toLocaleString('en-GB',{timeZone:'Europe/London'});
 if(tab==='Overview') return <><Panel title="Commercial policy overview"><div className="quote-rail-body">{fields([
 ['Cover starts',date(snapshot.term.startsAt)+' · London'],['Cover ends',date(snapshot.term.endsAt)+' · London'],['Renewal invitation','Not prepared'],['Selected issued version',String(policy.versionSequence)],
 ['Trade',text(risk.business?.description)],['Employee count','Not recorded'],['Locations',String(locations.length)],['Total property sum insured',amount(summary.total)],['Demo maximum estimated loss',amount(summary.demoMel)],
 ['Employers’ liability limit',amount(sections.find(x=>x.code==='employers-liability')?.limit)],['Public liability limit',amount(sections.find(x=>x.code==='public-liability')?.limit)],
 ['BI sum insured',amount(sections.find(x=>x.code==='business-interruption')?.limit)],['Servicing owner','Not recorded']])}<p>Demo maximum estimated loss is the largest location’s buildings, contents and stock total.</p></div></Panel>
 <Panel title="Premium at selected version"><div className="quote-rail-body">{fields([['Term premium',money(snapshot.premium.termPremium)],['Insurance premium tax',money(snapshot.premium.tax)],['Policy fee',money(snapshot.premium.fee)],['Gross payable',money(snapshot.premium.grossPayable)],['Broker commission',money(snapshot.premium.brokerCommission)]])}</div></Panel><CommercialExposurePanel policy={policy}/></>;
 if(tab==='Risk details') return <Panel title="Business and risk details" note={`Immutable declarations · version ${policy.versionSequence}`}><div className="quote-rail-body">{details({insured:snapshot.insured,business:risk.business})}<details><summary>Claims and losses</summary>{details(risk.losses??[])}</details><details><summary>Business declarations and material facts</summary>{details({declarations:risk.declarations,materialFacts:risk.materialFacts})}</details></div></Panel>;
 if(tab==='Cover') return <><Panel title="Selected commercial cover"><DataTable caption="Issued commercial cover sections" columns={['Section','Limit / sum insured','Excess','Basis / property reference']}>
 {sections.map((row,i)=><tr key={text(row.id)+i}><th scope="row">{sectionName(row.code)}</th><td>{amount(row.limit)}</td><td>{amount(row.excess)}</td><td>{Array.isArray(row.targetIds)&&row.targetIds.length?row.targetIds.map(id=>text(locations.find(x=>x.id===id)?.reference)).join(', '):text(row.basis)}</td></tr>)}</DataTable><div className="quote-rail-body"><p>Only issued sections appear here. Missing limits or excesses are shown as not recorded.</p><details><summary>Cover declarations and basis</summary>{details(snapshot.cover.responses)}</details></div></Panel>
 <Panel title="Endorsements and warranties"><div className="quote-rail-body">{details({endorsements:snapshot.cover.endorsements,warranties:snapshot.cover.warranties})}<p>Individual wording authors and effective dates were not captured in this snapshot. Source underwriting decisions are available from the source quote.</p></div></Panel></>;
 if(tab==='Property schedule') return <><Panel title="Locations and sums insured" note="Buildings + contents + stock at the selected version"><DataTable caption="Commercial property schedule" columns={['Reference / address','Use','Buildings','Contents','Stock','Total']}>
 {locations.map((location,index)=><tr key={location.id}><th scope="row">{text(location.reference)}<p>{['line1','line2','town','county','postcode'].map(key=>object(location.address)[key]).filter(x=>typeof x==='string').join(', ')}</p></th><td>{text(location.occupancy)}</td><td>{amount(location.buildings)}</td><td>{amount(location.contents)}</td><td>{amount(location.stock)}</td><td>{amount(summary.locationTotals[index])}</td></tr>)}</DataTable>
 <div className="quote-rail-body">{locations.map(location=><details key={location.id}><summary>{text(location.reference)} · construction, protections and declarations</summary>{details(location)}</details>)}</div></Panel><CommercialExposurePanel policy={policy}/></>;
 if(tab==='Liability & employees') return <><Panel title="Liability cover"><div className="quote-rail-body">{fields([['Employers’ liability limit',amount(sections.find(x=>x.code==='employers-liability')?.limit)],['Public liability limit',amount(sections.find(x=>x.code==='public-liability')?.limit)],['Products liability limit',amount(sections.find(x=>x.code==='products-liability')?.limit)],['Employers’ liability certificate',sections.some(x=>x.code==='employers-liability')?'Required · see Documents':'Not required']])}{details(risk.liability)}</div></Panel>
 <Panel title="Employees and annual wage roll" note="Employee headcounts were not captured; amounts below are annual wages"><DataTable caption="Declared wage categories" columns={['Category','Employee wages','Labour-only subcontractors','Bona fide subcontractors','Notes']}>
 {wages.map(row=><tr key={row.id}><th scope="row">{text(row.category)}</th><td>{amount(row.employees)}</td><td>{amount(row.labourOnlySubcontractors)}</td><td>{amount(row.bonaFideSubcontractors)}</td><td>{text(row.notes)}</td></tr>)}</DataTable><div className="quote-rail-body">{wages.map(row=><details key={row.id}><summary>{text(row.category)} · retained declarations</summary>{details(row.responses)}</details>)}</div></Panel></>;
 if(tab==='Business interruption') return <Panel title="Business interruption"><div className="quote-rail-body">{sections.some(x=>x.code==='business-interruption')?<>{fields([['Basis',sectionName(risk.businessInterruption?.basis)],['Sum insured',amount(risk.businessInterruption?.sumInsured)],['Indemnity period',typeof risk.businessInterruption?.indemnityMonths==='number'?`${risk.businessInterruption.indemnityMonths} months`:'Not recorded'],['Declaration linked',text(risk.businessInterruption?.declarationLinked)]])}{details({dependencies:risk.businessInterruption?.dependencies,responses:risk.businessInterruption?.responses})}</>:<p>Business interruption was not selected in this issued version.</p>}</div></Panel>;
 return null;
}
