'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {csrfToken,type Actor} from '../../lib/auth';
import {quoteFetch,uncertainQuoteFailure} from '../../lib/quotes';
import {sendServicing,servicingCommand,type ServicingCommand,type ServicingDraft,type ServicingEditor} from '../../lib/servicing-api';
import {matchingServicingEditor} from '../../lib/servicing-proposal';
import {funnelToMta,mtaToFunnel} from '../../lib/mta-funnel-adapter';
import {type FunnelCatalogue,type FunnelState} from '../../lib/funnel-adapter';
import {funnelOrigin,localFunnelParent} from '../../lib/funnel-origin';
import {LoadFeedback,useQuoteResource} from '../quotes/shared';
import {Panel} from '../primitives';
export function MtaFunnel({draftId,actorId,catalogue}:{draftId:string;actorId:string;catalogue:FunnelCatalogue}){
 const record=useQuoteResource<ServicingDraft>(`/api/v1/drafts/${draftId}`),editor=useQuoteResource<ServicingEditor>(`/api/v1/drafts/${draftId}/editor`);const [error,setError]=useState('');const [busy,setBusy]=useState(false),[acquirePending,setAcquirePending]=useState(false),[observedAt,setObservedAt]=useState(0);
 useEffect(()=>{queueMicrotask(()=>setObservedAt(Date.now()));},[record.data]);const pending=useRef<ServicingCommand|undefined>(undefined);
 async function acquire(){if(busy||!record.etag)return;setBusy(true);setError('');try{pending.current??=servicingCommand(`/api/v1/drafts/${draftId}/lease`,'POST',record.etag,{mode:'acquire'});await sendServicing(pending.current);pending.current=undefined;record.refresh();editor.refresh();}catch(failure){if(!uncertainQuoteFailure(failure))pending.current=undefined;setError(failure instanceof Error?failure.message:'Editing ownership could not be confirmed.');}finally{setAcquirePending(!!pending.current);setBusy(false);}}
 if(!record.data||!record.etag||!editor.data)return <Panel title="Motor Trade MTA"><LoadFeedback error={record.error||editor.error} retry={()=>{record.refresh();editor.refresh();}}/></Panel>;
 if(!matchingServicingEditor({data:record.data,etag:record.etag},{data:editor.data,etag:editor.etag??null}))return <Panel title="Draft changed"><p>Refresh the current draft before opening capture.</p><button className="button" onClick={()=>{record.refresh();editor.refresh();}}>Refresh draft</button></Panel>;
 if(record.data.kind!=='adjustment'||record.data.state!=='draft'||!['motor-trade-road-risks','motor-trade-combined'].includes(editor.data.assessment.base.productCode))return <Panel title="Capture unavailable"><Link href={`/drafts/${draftId}`}>Open saved draft</Link></Panel>;
 const lease=record.data.lease;
 if(!lease?.active||lease.holderId!==actorId||Date.parse(lease.expiresAt)<=observedAt)return <Panel title="Editing ownership required"><p>Acquire the current draft lease to edit the Motor Trade MTA. In-force cover stays unchanged.</p>{error&&<p role="alert">{error}</p>}<button className="button" disabled={busy||(!!lease?.active&&lease.holderId!==actorId&&Date.parse(lease.expiresAt)>observedAt)} onClick={()=>void acquire()}>{busy?'Acquiring…':acquirePending?'Retry same acquisition':'Acquire editing lease'}</button><Link className="button" href={`/drafts/${draftId}`}>Open MTA review</Link></Panel>;
 return <ConnectedMta key={`${draftId}:${actorId}`} initial={record.data} initialEditor={editor.data} initialEtag={record.etag} actorId={actorId} catalogue={catalogue}/>;
}
function ConnectedMta({initial,initialEditor,initialEtag,actorId,catalogue}:{initial:ServicingDraft;initialEditor:ServicingEditor;initialEtag:string;actorId:string;catalogue:FunnelCatalogue}){
 const router=useRouter(),frame=useRef<HTMLIFrameElement>(null);const [nonce]=useState(()=>crypto.randomUUID()),[parentOrigin,setParentOrigin]=useState('');const origin=funnelOrigin();
 const saved=useRef({draft:initial,editor:initialEditor,etag:initialEtag});const command=useRef<ServicingCommand|undefined>(undefined),leaseCommand=useRef<ServicingCommand|undefined>(undefined),lock=useRef(false),dirty=useRef(false),completion=useRef(false);const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[leasePending,setLeasePending]=useState(false);
 async function renew(){if(lock.current||command.current)return;lock.current=true;setBusy(true);setError('');const recovering=!!leaseCommand.current;let attempted=false;try{await csrfToken();const account=await quoteFetch<Actor>('/api/v1/account');if(account.data.id!==actorId)throw new Error('The signed-in account changed.');const current=saved.current;leaseCommand.current??=servicingCommand(`/api/v1/drafts/${initial.id}/lease`,'PUT',current.etag,undefined,current.draft.lease?.leaseToken);attempted=true;const result=await sendServicing(leaseCommand.current);const editor=await quoteFetch<ServicingEditor>(`/api/v1/drafts/${initial.id}/editor`);if(!matchingServicingEditor(result,editor))throw new Error('The renewed ownership readback is unconfirmed.');saved.current={draft:result.data,etag:result.etag,editor:editor.data};leaseCommand.current=undefined;setLeasePending(false);setNotice(`Editing lease renewed until ${new Date(result.data.lease!.expiresAt).toLocaleTimeString('en-GB')}. Your funnel answers are retained.`);}catch(failure){const uncertain=recovering&&leasePending||attempted&&uncertainQuoteFailure(failure);setLeasePending(uncertain);if(!uncertain)leaseCommand.current=undefined;setError(failure instanceof Error?failure.message:'Editing ownership could not be confirmed.');}finally{lock.current=false;setBusy(false);}}
 useEffect(()=>{queueMicrotask(()=>{if(localFunnelParent(window.location.origin))setParentOrigin(window.location.origin);else setError('This back-office address is not configured for Motor Trade capture.');});},[]);
 useEffect(()=>{const blocked=()=>lock.current||command.current||leaseCommand.current||dirty.current;const warn=()=>setError('Save and confirm the MTA changes before leaving.');const unload=(event:BeforeUnloadEvent)=>{if(blocked())event.preventDefault();};const click=(event:MouseEvent)=>{if(blocked()&&(event.target as Element).closest?.('a[href]')){event.preventDefault();event.stopPropagation();warn();}};const navigation=(window as Window & {navigation?:EventTarget}).navigation;const navigate=(event:Event)=>{if(blocked()&&event.cancelable){event.preventDefault();warn();}};window.addEventListener('beforeunload',unload);document.addEventListener('click',click,true);navigation?.addEventListener('navigate',navigate);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',click,true);navigation?.removeEventListener('navigate',navigate);};},[]);
 useEffect(()=>{
  const post=(message:Record<string,unknown>)=>frame.current?.contentWindow?.postMessage({...message,nonce},origin);
  async function save(state?:FunnelState,complete=false){if(lock.current||leaseCommand.current)return;const recovering=!!command.current;
   if(!command.current&&state){try{const current=saved.current;const proposal=funnelToMta(state,current.draft.proposal,current.editor,current.draft.policyId,catalogue);command.current=servicingCommand(`/api/v1/drafts/${initial.id}/funnel`,'PUT',current.etag,{proposal,funnelStateJson:JSON.stringify(state)},current.draft.lease?.leaseToken);completion.current=complete;}catch(failure){const message=failure instanceof Error?failure.message:'Review the MTA changes.';setError(message);post({type:'cx1:funnel-error',message});return;}}
   if(!command.current)return;lock.current=true;setBusy(true);setError('');let attempted=false;
   try{await csrfToken();const account=await quoteFetch<Actor>('/api/v1/account');if(account.data.id!==actorId)throw new Error('The signed-in account changed.');attempted=true;const result=await sendServicing(command.current);const editor=await quoteFetch<ServicingEditor>(`/api/v1/drafts/${initial.id}/editor`);if(!matchingServicingEditor(result,editor))throw new Error('The saved MTA readback is unconfirmed.');saved.current={draft:result.data,etag:result.etag,editor:editor.data};command.current=undefined;dirty.current=false;setPending(false);setNotice('MTA draft saved. In-force cover remains unchanged.');post({type:'cx1:funnel-saved',revisionId:result.data.revisionId,state:result.data.funnelStateJson?JSON.parse(result.data.funnelStateJson):undefined,url:`${window.location.origin}/drafts/${initial.id}`,readiness:{issues:editor.data.assessment.readinessIssues.map(issue=>({...issue,category:"capture",message:issue.code.replaceAll("-"," ")}))}});if(completion.current)router.replace(`/drafts/${initial.id}`);
   }catch(failure){const uncertain=recovering&&pending||(attempted&&uncertainQuoteFailure(failure));setPending(uncertain);if(!uncertain)command.current=undefined;const message=failure instanceof Error?failure.message:'The MTA result is unconfirmed.';setError(message);post({type:'cx1:funnel-error',message,pending:uncertain});}finally{lock.current=false;setBusy(false);}}
  const receive=(event:MessageEvent)=>{if(!localFunnelParent(window.location.origin)||event.origin!==origin||event.source!==frame.current?.contentWindow||event.data?.nonce!==nonce)return;const current=saved.current;
   if(event.data.type==='cx1:funnel-ready'){const state=current.draft.funnelStateJson?JSON.parse(current.draft.funnelStateJson):{version:1,step:1,formData:mtaToFunnel(current.draft.proposal,current.editor,catalogue)};post({type:'cx1:funnel-open',state,pending:!!command.current,context:{quoteId:initial.id,revisionId:current.draft.revisionId,reference:`MTA · ${initial.context?.policyReference??'Motor Trade policy'}`,clientName:initial.context?.clientName??String(current.editor.assessment.base.insured?.legalName??'Policyholder'),agencyName:initial.context?.agencyName??'Agency unavailable',productCode:current.editor.assessment.base.productCode,captureLimits:catalogue.captureLimits,captureKind:'mta'}});}
   if(event.data.type==='cx1:funnel-dirty')dirty.current=true;
   if(event.data.type==='cx1:funnel-save'&&!pending)void save(event.data.state,event.data.complete===true);
   if(event.data.type==='cx1:funnel-retry'&&pending)void save();
  };window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);
 },[actorId,catalogue,initial,nonce,origin,pending,router]);
 return <><div className="page-heading"><div><h1>Motor Trade MTA · {initial.context?.policyReference}</h1><p>Requested by {initial.proposal.requestedBy.kind}{initial.proposal.requestedBy.name?` · ${initial.proposal.requestedBy.name}`:''} · Effective {initial.proposal.commonEffectiveIntent.localDate} {initial.proposal.commonEffectiveIntent.localTime} London</p><p>Issued base {initial.baseVersionId} · Saved draft edits do not change in-force cover.</p></div><button className="button" disabled={busy||pending||leasePending} onClick={()=>frame.current?.contentWindow?.postMessage({type:'cx1:funnel-save-return',nonce},origin)}>Save and return to MTA</button><button className="button" disabled={busy||pending} onClick={()=>void renew()}>{leasePending?"Retry same lease renewal":"Renew editing lease"}</button></div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{parentOrigin&&<iframe inert={busy||leasePending} ref={frame} title="Motor Trade MTA funnel" className="quote-funnel-frame" src={`${origin}/?cx1Host=backoffice&parentOrigin=${encodeURIComponent(parentOrigin)}&nonce=${nonce}`}/>}</>;
}
