'use client';
import {useState} from 'react';
import {addCommercialRow,changeCommercialField,commercialField,commercialRows,commercialResponse,removeCommercialRow,sumCommercialMoney,updateCommercialRow,commercialReferenceVersion,type CommercialProposal} from '../../lib/commercial-capture';
import type {QuoteValue} from '../../lib/quotes';
import {CommercialInput,CommercialQuestionFields,type CommercialFormProps} from './commercial-question-fields';
import {CommercialItemDialog} from './commercial-item-dialog';
import {commercialMoney} from './commercial-location-stage';
import {clearSectionInputs} from './commercial-cover-stage';

export function CommercialLiabilityStage({form}:{form:CommercialFormProps}){
 const [edit,setEdit]=useState<{id:string;proposal:CommercialProposal;isNew:boolean}>();const rows=commercialRows(form.proposal,'wages');
 const el=form.catalogue.questions.find(q=>q.id==='prototype.quote.36ef01068295')!;const selected=commercialResponse(form.proposal,el);
 const set=(path:string,value:QuoteValue|undefined)=>form.replace(changeCommercialField(form.proposal,path,value));
 const limits=(path:string,label:string,choices:string[])=><label>{label}<select aria-label={label} value={String(commercialField(form.proposal,path)??'')} onChange={event=>set(path,event.target.value||undefined)}><option value="">Not answered</option>{choices.map(value=><option key={value} value={value}>{value==='0.00'?'Not required':commercialMoney(value)}</option>)}</select></label>;
 return <><CommercialQuestionFields form={form} questions={[el]}/>
  {selected!==true&&(rows.length>0||commercialField(form.proposal,'risk.liability.employersLimit')!==undefined||commercialField(form.proposal,'risk.liability.employersReferenceNumber')!==undefined)&&<div><p role="alert">Employers’ liability is not selected. Review the retained limit, ERN and wage details.</p><button className="button" type="button" onClick={()=>{if(window.confirm('Clear retained employers’ liability limit, ERN and all wage categories? Save the draft to record the removal.'))clearSectionInputs(form,'el');}}>Clear retained EL details</button></div>}
  <div className="quote-row-actions"><h3>Wage roll</h3><button className="button button-primary" type="button" disabled={rows.length>=100} onClick={()=>{const proposal=addCommercialRow(form.proposal,'wages');setEdit({id:commercialRows(proposal,'wages').at(-1)!.id,proposal,isNew:true});}}>Add wage category</button></div>
  {rows.length===0?<p className="empty-state">No wage categories added. Add employee and subcontractor wages, or review whether employers’ liability is required.</p>:<div className="table-scroll" role="region" aria-label="Commercial wage categories" tabIndex={0}><table><thead><tr><th>Category</th><th>Employees</th><th>Labour only subcontractors</th><th>Bona fide subcontractors</th><th>Total</th><th>Actions</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id}><th>{String((row.category as {label?:string}|undefined)?.label??'Not answered')}</th><td className="num">{commercialMoney(row.employees)}</td><td className="num">{commercialMoney(row.labourOnlySubcontractors)}</td><td className="num">{commercialMoney(row.bonaFideSubcontractors)}</td><td className="num">{commercialMoney(sumCommercialMoney([row.employees,row.labourOnlySubcontractors,row.bonaFideSubcontractors]))}</td><td><div className="quote-row-actions"><button className="button" type="button" onClick={()=>setEdit({id:row.id,proposal:structuredClone(form.proposal),isNew:false})}>Edit wage category {index+1}</button><button className="button" type="button" onClick={()=>{if(window.confirm(`Remove wage category ${index+1}? Save the draft to record the removal.`))form.replace(removeCommercialRow(form.proposal,'wages',row.id));}}>Remove wage category {index+1}</button></div></td></tr>)}</tbody></table></div>}
  <p>Total declared wage roll: <strong>{commercialMoney(sumCommercialMoney(rows.flatMap(row=>[row.employees,row.labourOnlySubcontractors,row.bonaFideSubcontractors])))}</strong>. Labour-only subcontractor wages are distinct from bona fide subcontractor amounts.</p>
  <fieldset className="quote-reference-fields"><legend>Liability limits and activities</legend><div className="quote-form-grid">
   {limits('risk.liability.employersLimit','Employers’ liability limit',['5000000.00','10000000.00'])}{limits('risk.liability.publicLimit','Public liability limit',['1000000.00','2000000.00','5000000.00','10000000.00'])}{limits('risk.liability.productsLimit','Products liability limit',['0.00','1000000.00','2000000.00','5000000.00','10000000.00'])}
   <CommercialInput form={form} inputKey="risk.liability.employersReferenceNumber" label="Employers reference number (ERN)" maxLength={100} value={commercialField(form.proposal,'risk.liability.employersReferenceNumber')} change={value=>set('risk.liability.employersReferenceNumber',value)}/>
   <CommercialInput form={form} inputKey="risk.liability.maximumHeightMetres" label="Maximum working height (metres)" kind="decimal" value={commercialField(form.proposal,'risk.liability.maximumHeightMetres')} change={value=>set('risk.liability.maximumHeightMetres',value)}/>
   <CommercialInput form={form} inputKey="risk.liability.hotWorksProcedures" label="Hot work procedures" kind="textarea" maxLength={2000} value={commercialField(form.proposal,'risk.liability.hotWorksProcedures')} change={value=>set('risk.liability.hotWorksProcedures',value)}/>
  </div><CommercialQuestionFields form={form} questions={form.catalogue.questions.filter(q=>q.stage===8&&!q.container.includes('[]'))}/></fieldset>
  {edit&&<CommercialItemDialog key={edit.id} title={edit.isNew?'Add wage category':'Edit wage category'} initial={edit.proposal} catalogue={form.catalogue} close={()=>setEdit(undefined)} apply={proposal=>{form.replace(proposal);setEdit(undefined);}}>{local=><WageFields form={local} id={edit.id}/>}</CommercialItemDialog>}
 </>;
}
function WageFields({form,id}:{form:CommercialFormProps;id:string}){
 const row=commercialRows(form.proposal,'wages').find(x=>x.id===id)!;const set=(path:string,value:QuoteValue|undefined)=>form.replace(updateCommercialRow(form.proposal,'wages',id,path,value));
 return <><div className="quote-form-grid"><label>Wage category<select aria-label="Wage category" value={String((row.category as {value?:string}|undefined)?.value??'')} onChange={event=>{const choice=form.catalogue.wageCategories.find(x=>x.value===event.target.value);set('category',choice?{collection:'cc-wage',...choice,version:commercialReferenceVersion}:undefined);}}><option value="">Not answered</option>{form.catalogue.wageCategories.map(choice=><option key={choice.value} value={choice.value}>{choice.label}</option>)}</select></label>
  {(['employees','labourOnlySubcontractors','bonaFideSubcontractors'] as const).map((path,index)=><CommercialInput key={path} form={form} inputKey={`${id}:${path}`} label={['Employee wages','Labour-only subcontractor wages','Bona fide subcontractor wages'][index]} kind="money" maxLength={30} value={row[path]} change={value=>set(path,value)}/>)}
  <CommercialInput form={form} inputKey={`${id}:notes`} label="Wage category notes" kind="textarea" maxLength={2000} value={row.notes} change={value=>set('notes',value)}/>
 </div><CommercialQuestionFields form={form} questions={form.catalogue.questions.filter(q=>q.container==='risk.wages[].responses')} itemId={id}/></>;
}
