'use client';
import {useEffect,useRef,useState} from 'react';
import {csrfToken,type Actor} from '../../lib/auth';
import {changeField,fieldValue,percentageInput} from '../../lib/quote-form';
import {quoteFetch,sendQuoteCommand,uncertainQuoteFailure,type PendingQuoteCommand,type QuoteProposal,type QuoteView} from '../../lib/quotes';
import type {QuoteFormCatalogue} from '../../lib/quote-catalogue';
import {QuotePremises} from './quote-premises';
import {QuoteSourceBusiness} from './quote-source-business';
import {QuoteDrivers} from './quote-drivers';
import {RequestedCover} from './requested-cover';
import {Panel} from '../primitives';
const shares=[['sales','Vehicle sales'],['servicing','Servicing'],['mechanicalRepair','Mechanical repair'],['breakdownRecovery','Breakdown and recovery'],['bodyRepairs','Body repairs'],['valeting','Valeting'],['other','Other activities']] as const;
export function QuoteReviewControls({quote,etag,actorId,catalogue,refresh,saveReviewed,blockedChanged}:{quote:Pick<QuoteView,'id'|'proposal'|'captureVersions'|'productCode'|'funnelStateJson'>&{capabilities:{canSave:boolean}};etag:string;actorId:string;catalogue:QuoteFormCatalogue;refresh:()=>void;saveReviewed?:(proposal:QuoteProposal)=>Promise<void>;blockedChanged?:(blocked:boolean)=>void}){
 const [proposal,setProposal]=useState<QuoteProposal>(()=>structuredClone(quote.proposal));const [buffers,setBuffers]=useState<Record<string,string>>({});const [invalid,setInvalid]=useState<Record<string,string>>({});
 const [busy,setBusy]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState('');const command=useRef<PendingQuoteCommand|undefined>(undefined);const lock=useRef(false);
 const guard=useRef(false);useEffect(()=>{guard.current=pending||busy||JSON.stringify(proposal)!==JSON.stringify(quote.proposal);},[pending,busy,proposal,quote.proposal]);
 useEffect(()=>{blockedChanged?.(pending||busy||JSON.stringify(proposal)!==JSON.stringify(quote.proposal));},[blockedChanged,pending,busy,proposal,quote.proposal]);
 useEffect(()=>{const warn=()=>setError('Save and confirm these review changes before leaving.');const unload=(event:BeforeUnloadEvent)=>{if(guard.current)event.preventDefault();};const click=(event:MouseEvent)=>{if(guard.current&&(event.target as Element).closest?.('a[href],.quote-tab,.record-header-actions button')){event.preventDefault();event.stopPropagation();warn();}};const navigation=(window as Window & {navigation?:EventTarget}).navigation;const navigate=(event:Event)=>{if(guard.current&&event.cancelable){event.preventDefault();warn();}};window.addEventListener('beforeunload',unload);document.addEventListener('click',click,true);navigation?.addEventListener('navigate',navigate);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',click,true);navigation?.removeEventListener('navigate',navigate);};},[]);
 const change=(path:string,value:Parameters<typeof changeField>[2])=>setProposal(current=>changeField(current,path,value));
 const validity=(path:string,message?:string)=>setInvalid(current=>{const next={...current};if(message)next[path]=message;else delete next[path];return next;});
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');let attempted=false;const recovering=pending;
  try{if(!saveReviewed&&!command.current)command.current=Object.freeze({url:`/api/v1/quotes/${quote.id}/proposal`,method:'PUT',etag,key:crypto.randomUUID(),expectedId:quote.id,body:JSON.stringify({proposal,reason:'Completed back-office risk review',...(quote.funnelStateJson?{funnelStateJson:quote.funnelStateJson}:{})})});
   const csrf=await csrfToken();const account=await quoteFetch<Actor>('/api/v1/account');if(account.data.id!==actorId)throw new Error('The signed-in account changed.');attempted=true;if(saveReviewed)await saveReviewed(proposal);else await sendQuoteCommand(command.current!,csrf);command.current=undefined;guard.current=false;setPending(false);refresh();
  }catch(failure){const uncertain=recovering||(attempted&&uncertainQuoteFailure(failure));setPending(uncertain);if(!uncertain)command.current=undefined;setError(failure instanceof Error?failure.message:'The saved result is unconfirmed.');}finally{lock.current=false;setBusy(false);}}
 const props={proposal,versions:quote.captureVersions,catalogue,buffers,validity,setBuffer:(key:string,value:string|undefined)=>setBuffers(current=>{const next={...current};if(value===undefined)delete next[key];else next[key]=value;return next;}),replace:setProposal};
 const premisesCatalogue={...catalogue,sectionFields:catalogue.sectionFields?.filter(field=>field.group==='premises'&&!field.id.startsWith('MTS-'))};
 const businessCatalogue={...catalogue,businessQuestions:catalogue.businessQuestions.filter(question=>question.id.startsWith('prototype.'))};
 const driverCatalogue={...catalogue,driverFields:catalogue.driverFields?.filter(field=>!field.id.startsWith('MTS-'))};
 return <Panel title="Complete risk review" note="Additional declarations required before rating"><div className="quote-rail-body"><p>Capture Motor Trade answers in the funnel, then confirm these additional business declarations. They remain separate from the occupation percentages.</p><fieldset disabled={busy||pending||!quote.capabilities.canSave} className="quote-selection"><legend className="sr-only">Additional risk declarations</legend>
 <div className="quote-form-grid">{[0,1,2].map(index=>{const names=proposal.insured?.proposerNames as string[]|undefined;return <label key={index}>Proposer {index+1} full name<input maxLength={200} value={names?.[index]??''} onChange={event=>{const next=Array.from({length:3},(_,at)=>names?.[at]??'');next[index]=event.target.value;while(next.length&&!next.at(-1))next.pop();change('insured.proposerNames',next.length?next:undefined);validity('names',next.some(name=>!name.trim())?'Enter every retained proposer name.':undefined);}}/></label>;})}</div>
 <div className="quote-form-grid"><label>Business description<textarea aria-label="Business description" rows={3} maxLength={4000} value={String(fieldValue(proposal,'risk.business.description')??'')} onChange={event=>change('risk.business.description',event.target.value||undefined)}/></label></div>
 <h3>Activity split</h3><div className="quote-form-grid">{shares.map(([name,label])=>{const path=`risk.business.declaredActivitySplit.${name}`;const value=fieldValue(proposal,path);return <label key={name}>{label} (%)<input inputMode="decimal" value={buffers[path]??(typeof value==='number'?String(value/100):'')} onChange={event=>{const text=event.target.value;setBuffers(current=>({...current,[path]:text}));const result=percentageInput(text);if(result.error)validity(path,result.error);else{validity(path);change(path,result.value);}}}/></label>;})}</div><p>Total declared activity: {shares.reduce((sum,[name])=>sum+Number(fieldValue(proposal,`risk.business.declaredActivitySplit.${name}`)??0),0)/100}%</p>
 <QuoteSourceBusiness proposal={proposal} versions={quote.captureVersions} catalogue={businessCatalogue} stage={1} replace={setProposal}/><QuoteSourceBusiness proposal={proposal} versions={quote.captureVersions} catalogue={businessCatalogue} stage={2} replace={setProposal}/>
 {(proposal.risk?.drivers as {id:string}[]|undefined)?.map(row=><QuoteDrivers key={row.id} {...props} targetId={row.id} catalogue={driverCatalogue}/>)}
 <h3>Driver history declarations</h3>{(proposal.risk?.drivers as {id:string}[]|undefined)?.map(row=><QuoteDrivers key={row.id} {...props} targetId={row.id} history catalogue={catalogue}/>)}
 {quote.productCode==='motor-trade-combined'&&<RequestedCover {...props}/>}
 {quote.productCode==='motor-trade-combined'&&<><h3>Premises cover</h3><p>Use the funnel to add premises addresses. Confirm insured sums, use and security for each retained premises.</p>{(proposal.risk?.premises as {id:string}[]|undefined)?.map(row=><QuotePremises key={row.id} {...props} targetId={row.id} catalogue={premisesCatalogue}/>)}</>}
 </fieldset>{error&&<p role="alert">{error}</p>}{Object.values(invalid).map(message=><p role="alert" key={message}>{message}</p>)}<button className="button button-primary" disabled={busy||!quote.capabilities.canSave||Object.keys(invalid).length>0} onClick={()=>void save()}>{busy?'Saving…':pending?'Retry same review save':'Save risk review'}</button></div></Panel>;
}
