'use client';
import {useEffect,useRef,useState} from 'react';
import {csrfToken,type Actor} from '../../lib/auth';
import {quoteFetch,sendQuoteCommand,uncertainQuoteFailure,type PendingQuoteCommand,type QuoteObject,type QuoteView} from '../../lib/quotes';
import {QuoteEvidence} from './quote-evidence';
import {QuoteLookupControl,QuoteLookupProvider} from './quote-lookup';
export function QuoteCaptureProof({quote,etag,actorId,refresh}:{quote:QuoteView;etag:string;actorId:string;refresh:()=>void}){
 const command=useRef<PendingQuoteCommand|undefined>(undefined);const lock=useRef(false);const [busy,setBusy]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const unload=(event:BeforeUnloadEvent)=>{if(lock.current||command.current)event.preventDefault();};const click=(event:MouseEvent)=>{if((lock.current||command.current)&&(event.target as Element).closest?.('a[href],.quote-tab,.record-header-actions button')){event.preventDefault();event.stopPropagation();setError('Confirm the pending proof action before leaving.');}};window.addEventListener('beforeunload',unload);document.addEventListener('click',click,true);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',click,true);};},[]);
 async function run(next?:PendingQuoteCommand){if(lock.current)return;if(!command.current)command.current=next;if(!command.current)return;lock.current=true;setBusy(true);setError('');let attempted=false;
 try{const csrf=await csrfToken();const account=await quoteFetch<Actor>('/api/v1/account');if(account.data.id!==actorId)throw new Error('The signed-in account changed.');attempted=true;await sendQuoteCommand(command.current,csrf);command.current=undefined;setPending(false);refresh();}catch(failure){const uncertain=pending||(attempted&&uncertainQuoteFailure(failure));setPending(uncertain);if(!uncertain)command.current=undefined;setError(failure instanceof Error?failure.message:'The action could not be confirmed.');}finally{lock.current=false;setBusy(false);}}
 return <>{error&&<p role="alert">{error}</p>}{pending&&<button className="button" disabled={busy} onClick={()=>void run()}>Retry same proof action</button>}<QuoteLookupProvider saved={quote} etag={etag} disabled={busy||pending||!quote.capabilities.canSave} dirty={false} refreshToken={0} run={next=>void run(next)}><QuoteEvidence saved={quote} etag={etag} disabled={busy||pending} dirty={false} refreshToken={0} run={next=>void run(next)}/><details><summary>Address and vehicle declarations</summary><p>Record the lookup outcome or explain a manual decision for the saved details. Manual entry does not imply provider verification.</p><QuoteLookupControl kind="address" scope="insured" label="Proposer address"/>{(quote.proposal.risk?.premises as QuoteObject[]|undefined)?.map((row,index)=><QuoteLookupControl key={String(row.id)} kind="address" scope="premises" riskItemId={String(row.id)} label={`Premises ${index+1} address`}/>)}{(quote.proposal.risk?.vehicles as QuoteObject[]|undefined)?.map((row,index)=><QuoteLookupControl key={String(row.id)} kind="vehicle" scope="vehicle" riskItemId={String(row.id)} label={`Vehicle ${index+1}`}/>)}</details></QuoteLookupProvider></>;
}
