// <auto-generated />
using System;
using BackOffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackOffice.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BackOfficeDbContext))]
    [Migration("20260913181239_ProductValidityGuard")]
    partial class ProductValidityGuard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.AdapterAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorkId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("AdapterAttempt", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdapterAttempt_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_AdapterAttempt_EndedAt_Utc", "DATEPART(TZOFFSET,[EndedAt]) = 0");

                            t.HasCheckConstraint("CK_AdapterAttempt_Number", "[AttemptNumber] > 0");

                            t.HasCheckConstraint("CK_AdapterAttempt_Request_Json", "ISJSON([Request]) = 1");

                            t.HasCheckConstraint("CK_AdapterAttempt_Response_Json", "[Response] IS NULL OR ISJSON([Response]) = 1");

                            t.HasCheckConstraint("CK_AdapterAttempt_StartedAt_Utc", "DATEPART(TZOFFSET,[StartedAt]) = 0");

                            t.HasCheckConstraint("CK_AdapterAttempt_Times", "[EndedAt] IS NULL OR [EndedAt] >= [StartedAt]");

                            t.HasCheckConstraint("CK_AdapterAttempt_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.AdapterInbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("QuarantineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorkId");

                    b.HasIndex("Provider", "EventId")
                        .IsUnique();

                    b.ToTable("AdapterInbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdapterInbox_AppliedAt_Utc", "DATEPART(TZOFFSET,[AppliedAt]) = 0");

                            t.HasCheckConstraint("CK_AdapterInbox_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_AdapterInbox_State", "[State] IN ('received','applied','quarantined')");

                            t.HasCheckConstraint("CK_AdapterInbox_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("After")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Before")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("SubjectRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ActorId", "OccurredAt");

                    b.HasIndex("SubjectRecordId", "OccurredAt");

                    b.ToTable("AuditEvent", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditEvent_After_Json", "[After] IS NULL OR ISJSON([After]) = 1");

                            t.HasCheckConstraint("CK_AuditEvent_Before_Json", "[Before] IS NULL OR ISJSON([Before]) = 1");

                            t.HasCheckConstraint("CK_AuditEvent_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_AuditEvent_OccurredAt_Utc", "DATEPART(TZOFFSET,[OccurredAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.CapacityProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("CapacityProvider", null, t =>
                        {
                            t.HasCheckConstraint("CK_CapacityProvider_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_CapacityProvider_State", "[State] IN ('active','inactive')");

                            t.HasCheckConstraint("CK_CapacityProvider_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.DemoClock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FrozenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DemoClock", null, t =>
                        {
                            t.HasCheckConstraint("CK_DemoClock_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_DemoClock_FrozenAt_Utc", "DATEPART(TZOFFSET,[FrozenAt]) = 0");

                            t.HasCheckConstraint("CK_DemoClock_Singleton", "[Name] = 'demo'");

                            t.HasCheckConstraint("CK_DemoClock_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.DemoProviderOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ScenarioVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ScenarioVersionId");

                    b.HasIndex("Kind", "OperationKey")
                        .IsUnique();

                    b.ToTable("DemoProviderOperation", null, t =>
                        {
                            t.HasCheckConstraint("CK_DemoProviderOperation_CompletedAt_Utc", "DATEPART(TZOFFSET,[CompletedAt]) = 0");

                            t.HasCheckConstraint("CK_DemoProviderOperation_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_DemoProviderOperation_Result_Json", "[Result] IS NULL OR ISJSON([Result]) = 1");

                            t.HasCheckConstraint("CK_DemoProviderOperation_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorScope")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ResultBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResultStatus")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ActorScope", "Route", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecord", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdempotencyRecord_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_IdempotencyRecord_ExpiresAt_Utc", "DATEPART(TZOFFSET,[ExpiresAt]) = 0");

                            t.HasCheckConstraint("CK_IdempotencyRecord_ResultBody_Json", "ISJSON([ResultBody]) = 1");

                            t.HasCheckConstraint("CK_IdempotencyRecord_Status", "[ResultStatus] BETWEEN 100 AND 599");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.OutboxWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SubjectRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Kind", "OperationKey")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("OutboxWork", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutboxWork_Attempts", "[Attempts] >= 0");

                            t.HasCheckConstraint("CK_OutboxWork_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_OutboxWork_LeaseExpiresAt_Utc", "DATEPART(TZOFFSET,[LeaseExpiresAt]) = 0");

                            t.HasCheckConstraint("CK_OutboxWork_NextAttemptAt_Utc", "DATEPART(TZOFFSET,[NextAttemptAt]) = 0");

                            t.HasCheckConstraint("CK_OutboxWork_Payload_Json", "ISJSON([Payload]) = 1");

                            t.HasCheckConstraint("CK_OutboxWork_Result_Json", "[Result] IS NULL OR ISJSON([Result]) = 1");

                            t.HasCheckConstraint("CK_OutboxWork_State", "[State] IN ('pending','leased','succeeded','failed')");

                            t.HasCheckConstraint("CK_OutboxWork_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("Product", null, t =>
                        {
                            t.HasCheckConstraint("CK_Product_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_Product_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.ProductVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JsonSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionSetVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique();

                    b.ToTable("ProductVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductVersion_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_ProductVersion_Definition_Json", "ISJSON([Definition]) = 1");

                            t.HasCheckConstraint("CK_ProductVersion_EffectiveFrom_Utc", "DATEPART(TZOFFSET,[EffectiveFrom]) = 0");

                            t.HasCheckConstraint("CK_ProductVersion_EffectiveTo_Utc", "DATEPART(TZOFFSET,[EffectiveTo]) = 0");

                            t.HasCheckConstraint("CK_ProductVersion_State", "[State] IN ('draft','published','retired')");

                            t.HasCheckConstraint("CK_ProductVersion_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");

                            t.HasCheckConstraint("CK_ProductVersion_Validity", "[EffectiveTo] IS NULL OR [EffectiveTo] > [EffectiveFrom]");

                            t.HasCheckConstraint("CK_ProductVersion_Version", "[Version] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("Role", null, t =>
                        {
                            t.HasCheckConstraint("CK_Role_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_Role_Scope", "[Scope] IN ('internal','agency')");

                            t.HasCheckConstraint("CK_Role_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.SettingVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Scope", "Version")
                        .IsUnique();

                    b.ToTable("SettingVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_SettingVersion_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_SettingVersion_EffectiveFrom_Utc", "DATEPART(TZOFFSET,[EffectiveFrom]) = 0");

                            t.HasCheckConstraint("CK_SettingVersion_Values_Json", "ISJSON([Values]) = 1");

                            t.HasCheckConstraint("CK_SettingVersion_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("User", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_User_State", "[State] IN ('invited','active','suspended')");

                            t.HasCheckConstraint("CK_User_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Team", null, t =>
                        {
                            t.HasCheckConstraint("CK_Team_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_Team_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("MfaSecretCiphertext")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("MustReset")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("UserCredential", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserCredential_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_UserCredential_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRole", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserRole_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_UserRole_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("Session", null, t =>
                        {
                            t.HasCheckConstraint("CK_Session_CreatedAt_Utc", "DATEPART(TZOFFSET,[CreatedAt]) = 0");

                            t.HasCheckConstraint("CK_Session_ExpiresAt_Utc", "DATEPART(TZOFFSET,[ExpiresAt]) = 0");

                            t.HasCheckConstraint("CK_Session_Expiry", "[ExpiresAt] > [CreatedAt]");

                            t.HasCheckConstraint("CK_Session_LastSeenAt_Utc", "DATEPART(TZOFFSET,[LastSeenAt]) = 0");

                            t.HasCheckConstraint("CK_Session_RevokedAt_Utc", "DATEPART(TZOFFSET,[RevokedAt]) = 0");

                            t.HasCheckConstraint("CK_Session_UpdatedAt_Utc", "DATEPART(TZOFFSET,[UpdatedAt]) = 0");
                        });
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.AdapterAttempt", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.OutboxWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.AdapterInbox", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.OutboxWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.AuditEvent", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.CapacityProvider", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.DemoClock", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.DemoProviderOperation", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.SettingVersion", null)
                        .WithMany()
                        .HasForeignKey("ScenarioVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.OutboxWork", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.Product", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.ProductVersion", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackOffice.Infrastructure.Persistence.CapacityProvider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.Role", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.SettingVersion", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.StaffUser", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.Team", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.UserCredential", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.UserRole", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BackOffice.Infrastructure.Persistence.UserSession", b =>
                {
                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Infrastructure.Persistence.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
